feat(storybook): Deprecate CSS components
scania-digital-design-system/sdds pull request #1015
Opened 2023-04-19 12:04 UTC by timrombergjakobsson

**Describe pull-request**  
In move towards the final removal of Native(css) components for the Tegel package we start with separating them in Storybook. 

**Solving issue**  
Fixes:[DTS-1469](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?assignee=63ff6d6c314f5088138187f0&selectedIssue=DTS-1469)

**How to test**  
Pull down the branch and build it and run storybook and click around and make sure that everything works. 
**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-04-19 12:42 UTC, timrombergjakobsson commented on tegel/src/components/stepper/sdds-stepper.stories.tsx
>  import { formatHtmlPreview } from '../../utils/utils';
Changed to ```.tsx``` instead.

2023-04-20 12:05 UTC, mJarsater approved these changes
🦄

2023-04-20 12:34 UTC, theJohnnyMe approved these changes
LGTM ;) Rock it!

2023-04-20 12:59 UTC, mJarsater requested changes
The deprecation needs to be communicated in some way before this is merged.

2023-04-24 08:44 UTC, mJarsater commented
This needs a section in the migration docs.

2023-04-25 12:51 UTC, mJarsater approved these changes
🚀

2023-04-25 15:28 UTC, mJarsater requested changes
Looks like this needs a rebase

2023-04-25 15:31 UTC, timrombergjakobsson commented
> Looks like this needs a rebase

yep! Will do asap!

2023-04-25 15:32 UTC, mJarsater commented
> > Looks like this needs a rebase
> 
> yep! Will do asap!

No rush! Im thinking we'll hold off on the announcement until tomorrow! ✌️

2023-04-26 06:38 UTC, mJarsater reviewed
Nice! Do you wanna do the same thing for the Header and Side menu in this PR also?

2023-04-26 06:43 UTC, timrombergjakobsson commented
> Nice! Do you wanna do the same thing for the Header and Side menu in this PR also?

Sure thing!

2023-04-26 07:16 UTC, mJarsater approved these changes
LGTM!

2023-04-26 07:25 UTC, merged