feat(header,side-menu): fix dark mode color issues
scania-digital-design-system/sdds pull request #1018
Opened 2023-04-20 15:59 UTC by alexandereneroth

**Describe pull-request**  
Fixes darkmode color issues in header and sidemenu.

**Solving issue**  
Fixes: #DTS-717

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-04-25 07:56 UTC, nathalielindqvist reviewed
Seems like the variable --sdds-header-app-launcher-menu-bg is undefined, should we have that? Also the icons in the app launcher does not change color in dark mode, maybe we should introduce a variable for them? Currently the color is set using a static color.
![image](https://user-images.githubusercontent.com/48509966/234205187-0c22ed00-5993-498c-ad68-86f46088c2d6.png)

2023-04-25 07:56 UTC, nathalielindqvist commented on tegel/src/components/side-menu/webcomponent/side-menu-item/side-menu-item.scss
>        color: var(--sdds-sidebar-side-menu-single-item-color);
Looks like the icon in dark mode i Grey300 in Figma while the text is Grey50, has this changed?
![image](https://user-images.githubusercontent.com/48509966/234209377-0a12cfd8-8b1d-45f7-a10d-b5c7088581be.png)

2023-04-25 07:57 UTC, nathalielindqvist reviewed
EDIT: TEMPORARY BUG - WORKS NOW

Did we remove the collapse button?
![image](https://user-images.githubusercontent.com/48509966/234212124-305a46e9-1da5-4890-a0b5-bbcc2777cd5f.png)

2023-04-25 08:06 UTC, nathalielindqvist commented on tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.scss
> +      background-color: var(--sdds-grey-868);
Should we maybe introduce a variable for this color to account for dark/light mode? :)
![image](https://user-images.githubusercontent.com/48509966/234213679-1be67fb1-3324-4add-9091-846060075ec0.png)

2023-04-25 08:06 UTC, nathalielindqvist commented on tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.scss
> +      background-color: var(--sdds-grey-868);
Should we maybe introduce a variable for this color to account for dark/light mode? :)
![image](https://user-images.githubusercontent.com/48509966/234213679-1be67fb1-3324-4add-9091-846060075ec0.png)

2023-04-26 07:35 UTC, theJohnnyMe requested changes
In two places there are "--" missing in front of the variable.
I will take more detailed look after stand up today to compare colors here and in figma.

2023-04-26 07:35 UTC, theJohnnyMe commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +    background-color: var(sdds-grey-800);
```suggestion
    background-color: var(--sdds-grey-800);
```

2023-04-26 07:35 UTC, theJohnnyMe commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +      background-color: var(sdds-grey-800);
```suggestion
      background-color: var(--sdds-grey-800);
```

2023-04-26 07:36 UTC, theJohnnyMe commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +    background-color: var(sdds-grey-800);
Maybe this should be variable to easily switch between modes. Not sure yet. Please double check.

2023-04-26 07:36 UTC, theJohnnyMe commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +      background-color: var(sdds-grey-800);
Maybe this should be variable to easily switch between modes. Not sure yet. Please double check.

2023-04-27 10:32 UTC, mJarsater commented
Not really part of this PR, but the launcher seems to be in a active state by default?
<img width="340" alt="Screenshot 2023-04-26 at 10 41 35" src="https://user-images.githubusercontent.com/62651103/234837049-8da48072-b113-4f80-9602-c1b8f71c8459.png">

2023-04-27 16:11 UTC, alexandereneroth commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +    background-color: var(sdds-grey-800);
Yes, it definitely should. Good spot

2023-04-28 06:13 UTC, nathalielindqvist reviewed
Seems like there might be a dark mode variable kicking in on a pressed state? It only flashes by for a second so quite hard to catch

https://user-images.githubusercontent.com/48509966/235068588-6f818537-8d2d-4532-ace8-e2aca6c61728.mp4

2023-04-28 12:38 UTC, timrombergjakobsson commented
> Seems like there might be a dark mode variable kicking in on a pressed state? It only flashes by for a second so quite hard to catch
> 
>  Side.menu.web.component.-.dark.mode.color.in.light.mode.pressed.mp4

I can have a look at that.

2023-04-28 13:14 UTC, mJarsater commented
> ### ✅ Deploy Preview for _tegel-storybook_ ready!
> Name	Link
> 🔨 Latest commit	[088e72c](https://github.com/scania-digital-design-system/sdds/commit/088e72cd3aa31ccb96ccd311d60e287d7126deeb)
> 🔍 Latest deploy log	https://app.netlify.com/sites/tegel-storybook/deploys/644bc57adc473f0008f2786f
> 😎 Deploy Preview	https://deploy-preview-1018--tegel-storybook.netlify.app
> 📱 Preview on mobile	
> Toggle QR Code...
> _To edit notification comments on pull requests, go to your [Netlify site settings](https://app.netlify.com/sites/tegel-storybook/settings/deploys#deploy-notifications)._

I think this is the mobile menu, and that one is not collapseble as far as I know

2023-04-28 13:15 UTC, mJarsater commented
> EDIT: TEMPORARY BUG - WORKS NOW
> 
> Did we remove the collapse button? ![image](https://user-images.githubusercontent.com/48509966/234212124-305a46e9-1da5-4890-a0b5-bbcc2777cd5f.png)

I think this is the mobile menu, and that one is not collapseble as far as I know

2023-04-28 13:27 UTC, timrombergjakobsson commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +    background-color: var(sdds-grey-800);
Is this one even suppose to have a hover state?

2023-04-28 13:28 UTC, timrombergjakobsson commented on tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.scss
> +      background-color: var(--sdds-header-nav-item-dropdown-opened-background-active) !important;
Why do we need the `!important`-flag here?

2023-04-28 13:33 UTC, timrombergjakobsson commented on tegel/src/components/header/webcomponent/header-item/header-item.scss
> +    background-color: var(sdds-grey-800);
Maybe I'm just very tired but can't find a hover state in Figma.

2023-04-28 14:57 UTC, mJarsater approved these changes
Loooking gooood 🚀

2023-05-02 07:25 UTC, alexandereneroth commented on tegel/src/components/side-menu/webcomponent/side-menu-dropdown-list-item/side-menu-dropdown-list-item.scss
> +      background-color: var(--sdds-header-nav-item-dropdown-opened-background-active) !important;
I put it there since :active needs higher specificity than :hover to work reliably. 
I thought it was a decent use-case of !important, even though its true it should be avoided most times.

2023-05-02 07:26 UTC, alexandereneroth commented
> In two places there are "--" missing in front of the variable. I will take more detailed look after stand up today to compare colors here and in figma.

@mJarsater Is this fixed?
In that case lets dismiss the review since Johnny is on vacation

2023-05-02 07:29 UTC, mJarsater commented
> > In two places there are "--" missing in front of the variable. I will take more detailed look after stand up today to compare colors here and in figma.
> 
> @mJarsater Is this fixed? In that case lets dismiss the review since Johnny is on vacation

Not sure what Johnny meant with those. I just pushed a fix for these though, https://github.com/scania-digital-design-system/sdds/pull/1018#pullrequestreview-1399325138

I would say that you can dismiss his reviews for now.

2023-05-02 07:31 UTC, timrombergjakobsson commented
> > > In two places there are "--" missing in front of the variable. I will take more detailed look after stand up today to compare colors here and in figma.
> > 
> > 
> > @mJarsater Is this fixed? In that case lets dismiss the review since Johnny is on vacation
> 
> Not sure what Johnny meant with those. I just pushed a fix for these though, [#1018 (review)](https://github.com/scania-digital-design-system/sdds/pull/1018#pullrequestreview-1399325138)
> 
> I would say that you can dismiss his reviews for now.

I think he was referring to this:

https://github.com/scania-digital-design-system/sdds/pull/1018/files#r1177462399

2023-05-02 07:34 UTC, alexandereneroth commented
> > > > In two places there are "--" missing in front of the variable. I will take more detailed look after stand up today to compare colors here and in figma.
> > > 
> > > 
> > > @mJarsater Is this fixed? In that case lets dismiss the review since Johnny is on vacation
> > 
> > 
> > Not sure what Johnny meant with those. I just pushed a fix for these though, [#1018 (review)](https://github.com/scania-digital-design-system/sdds/pull/1018#pullrequestreview-1399325138)
> > I would say that you can dismiss his reviews for now.
> 
> I think he was referring to this:
> 
> [#1018 (files)](https://github.com/scania-digital-design-system/sdds/pull/1018/files#r1177462399)

Ah yea that looks like it needs fixing

2023-05-02 07:42 UTC, mJarsater commented
> > > > > In two places there are "--" missing in front of the variable. I will take more detailed look after stand up today to compare colors here and in figma.
> > > > 
> > > > 
> > > > @mJarsater Is this fixed? In that case lets dismiss the review since Johnny is on vacation
> > > 
> > > 
> > > Not sure what Johnny meant with those. I just pushed a fix for these though, [#1018 (review)](https://github.com/scania-digital-design-system/sdds/pull/1018#pullrequestreview-1399325138)
> > > I would say that you can dismiss his reviews for now.
> > 
> > 
> > I think he was referring to this:
> > [#1018 (files)](https://github.com/scania-digital-design-system/sdds/pull/1018/files#r1177462399)
> 
> Ah yea that looks like it needs fixing

Pushed a fix now

2023-05-02 07:53 UTC, alexandereneroth commented on tegel/src/components/side-menu/webcomponent/side-menu-item/side-menu-item.scss
>        color: var(--sdds-sidebar-side-menu-single-item-color);
I think its just this one left. Checked and this PR uses grey-50 which is inherited from the text color of the link/button. 
The icon color needs to be set on the global class __sdds-side-menu-item-icon

2023-05-02 07:54 UTC, alexandereneroth commented
Last thing I think https://github.com/scania-digital-design-system/sdds/pull/1018/files#r1182207121

2023-05-02 07:58 UTC, alexandereneroth commented
And one more: I believe this one should be grey-700 --sdds-header-app-launcher-grid-hover-background: var(--sdds-grey-500);

2023-05-02 08:03 UTC, mJarsater commented
> And one more: I believe this one should be grey-700 --sdds-header-app-launcher-grid-hover-background: var(--sdds-grey-500);

fixed

2023-05-03 06:35 UTC, merged