feat(data table): event refactoring and removal of props
scania-digital-design-system/sdds pull request #1025
Opened 2023-04-25 11:35 UTC by mJarsater

**Describe pull-request**  
This PR refactors the events in the data-table. It also removes the following props: 
`disableFilteringFunction`, `disableSortingFunction` and `enableClientPagination`

It introduces the following events:  `sddsPageChange`, `sddsSortChange`, `sddsFilterChange`
These can be prevented by a user to achieve the same effect as the props above. 

This is more inline with how other components work.

Also added a section in the migration docs to outline the breaking changes.

**Solving issue**  
Fixes: https://tegel.atlassian.net/browse/DTS-1479

**How to test**  
1. Go to storybook link below
2. Check in Data Table -> Web Components -> Sorting, Filtering, Pagination
3. Trigger the event for the corresponding story and look in to console for a log of the event. 
4. Check out the branch
5. Add preventDefault() to the event and see it fail. 

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-04-25 11:35 UTC, mJarsater commented on tegel/src/components/data-table/table-toolbar/table-toolbar.tsx
> +    // What does this do?
```suggestion
```

2023-04-25 11:56 UTC, mJarsater commented on tegel/src/components/data-table/table-header-cell/table-header-cell.tsx
> +  @State() sortingDirection: 'asc' | 'desc';
```suggestion
  @State() sortingDirection: 'asc' | 'desc' = null;
```

2023-04-25 11:57 UTC, mJarsater commented
> Testing it out in Storybook, saw that the hover is not showing the arrows on sorting instance. ![Skärmavbild 2023-04-25 kl 13 46 15](https://user-images.githubusercontent.com/201671/234266822-1cdc81d1-00a2-4d54-945e-3c95d1165406.png)
> 
> The sorting arrows shows however when clicking them, as per usual.

Great find! I think it was due to sortingDirection not being set to null by default. Pushed a change now that should fix it.

2023-04-25 11:59 UTC, timrombergjakobsson commented
> > Testing it out in Storybook, saw that the hover is not showing the arrows on sorting instance. ![Skärmavbild 2023-04-25 kl 13 46 15](https://user-images.githubusercontent.com/201671/234266822-1cdc81d1-00a2-4d54-945e-3c95d1165406.png)
> > The sorting arrows shows however when clicking them, as per usual.
> 
> Great find! I think it was due to sortingDirection not being set to null by default. Pushed a change now that should fix it.

Nice! Was just gonna push the same haha, your quicker!

2023-04-26 13:35 UTC, theJohnnyMe commented on tegel/src/components/data-table/table-body/table-body.tsx
> +        // TODO: EMIT PAGINATION
TODO comment : Is this still relevant? Do we need it?

2023-04-26 13:38 UTC, theJohnnyMe commented on tegel/src/components/data-table/table-footer/table-footer.tsx
> -
Nice clean up!

2023-04-26 13:41 UTC, theJohnnyMe requested changes
Pagination and Sorting stories are trowing issues in the console regarding the value and null, please double check.

2023-04-26 13:45 UTC, theJohnnyMe commented
Other than the null issue in the console, really great work man! 
I have tested it to prevent all three events, works like a charm! 🚀

2023-04-26 14:16 UTC, mJarsater commented on tegel/src/components/data-table/table-body/table-body.tsx
> +        // TODO: EMIT PAGINATION
Nope! NIce catch 🎣 I'll push a commit to remove it.

2023-04-26 14:17 UTC, mJarsater commented
> Pagination and Sorting stories are trowing issues in the console regarding the value and null, please double check.

Totally forgot about those! Pushed a fix now 😃

2023-04-27 14:04 UTC, timrombergjakobsson approved these changes
🚢

2023-04-27 14:12 UTC, merged