Improvement/update demo html
scania-digital-design-system/sdds pull request #110
Opened 2021-03-23 13:41 UTC by iths-jonathan-engman

**Describe pull-request**  
Showcasing components with a html demo

**How to test**  
Run live server on demo/html/index.html

**Additional context**  
Feel free to comment on the design and text content

2021-03-24 07:40 UTC, mmexvr requested changes
Update the readme file in the html project also, that is the most important one 

You can rewrite the whole thing

Maybe something like this can be added: 
- Explain what it is
- How to install theme and components

2021-03-24 08:28 UTC, mmexvr requested changes
Try and use our variables when setting size/color and so on from our foundation :)

2021-03-24 08:28 UTC, mmexvr commented on demo/HTML/html.css
> +    padding: 0;
We shoudn't effect the grid css at all, since that is what people use to position things. If we effect the grid from our own css that we can make sure the layout works

2021-03-24 08:28 UTC, mmexvr commented on demo/HTML/html.css
> +  background: #f6f6f7;
Try and use our variables, maybe add the `var(--sdds-grey-100)` or something, have a look at our background color on SDDS website

2021-03-24 08:28 UTC, mmexvr commented on demo/HTML/html.css
> +  font-size: 16px;
Same here, try and use the typography package to set the size of the p element. Follow the typography package documentation

2021-03-24 08:28 UTC, mmexvr commented on demo/HTML/html.css
> +  color: #9CA5C2;
Use our css variables instead

2021-03-24 08:28 UTC, mmexvr commented on demo/HTML/html.css
> +  background: #f6f6f7;
Or use classes that are avaliable

2021-03-24 08:38 UTC, mmexvr commented on demo/HTML/html.css
> +  font-size: 16px;
or use classes on the p to make it work

2021-03-31 10:05 UTC, helloimela approved these changes
Nice! good job!

2021-03-31 13:26 UTC, mmexvr approved these changes

2021-03-31 13:26 UTC, merged