Improvement/update demo react
scania-digital-design-system/sdds pull request #116
Opened 2021-03-30 09:43 UTC by iths-jonathan-engman

**Describe pull-request**  
A fresh installation of React demo

**Solving issue**  
Updated React demo with fresh installation

**How to test**  
-- Pull down
-- Initiate the project

**Issues**
-- On line 38 in components/main/Main.js, the "a" element doesn't href to anything, and React doesnt like that. If a dummy link is set, the disabled breadcrumb doesn't get "disabled".

**Screenshots**  
![image](https://user-images.githubusercontent.com/54362354/112968896-0954e500-914d-11eb-8cee-ad22a8f79d3d.png)
![image](https://user-images.githubusercontent.com/54362354/112968950-1540a700-914d-11eb-8713-ab28fbb7f49d.png)

2021-03-31 14:17 UTC, mmexvr requested changes

2021-03-31 14:17 UTC, mmexvr commented on demo/react/src/App.js
> +import Header from './components/header/Header';
Match the exact name with uppercase or not :)

2021-03-31 15:09 UTC, mmexvr approved these changes

2021-04-01 08:01 UTC, helloimela commented
Same here, make sure package-lock.json contains the latest package name and no changes occured when you run npm i once again. Check also in Vue PR #118

2021-04-01 08:07 UTC, helloimela commented on demo/react/public/manifest.json
> +      "src": "logo192.png",
Is this file exist somewhere? What is this image used for?
I got this error on the browser 
![image](https://user-images.githubusercontent.com/1199101/113263321-e6a00900-92d1-11eb-89b7-d58f9bfed00b.png)

2021-04-01 08:08 UTC, helloimela commented on demo/react/public/manifest.json
> +      "src": "logo512.png",
same with this one

2021-04-01 08:41 UTC, helloimela approved these changes

2021-04-01 08:41 UTC, merged