WIP: Remake commit
scania-digital-design-system/sdds pull request #145
Opened 2021-05-14 11:16 UTC by iths-jonathan-engman

**Describe pull-request**  
_Describe what the pull-request is about_

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #

**How to test**  
_Add description how to test if possible_

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

2021-05-17 09:42 UTC, helloimela requested changes

2021-05-17 09:42 UTC, helloimela commented on theme/light/src/components/_toasts.scss
> +  --sdds-toasts-background-color: #{get-colour(grey-900)};
Use prefix for the "sdds". See example in "sdds/theme/light/src/components/_textfield.scss"

2021-05-17 09:42 UTC, helloimela commented on theme/light/src/components/_toasts.scss
> +  --sdds-toasts-background-color: #{get-colour(grey-900)};
--#{$prefix}-

2021-05-17 12:03 UTC, helloimela requested changes
Can you rename all files from toasts to toast ?

2021-05-17 12:20 UTC, iths-jonathan-engman commented
> Can you rename all files from toasts to toast ?

Noticed that tooltip(s) need the same intervention

2021-05-17 13:10 UTC, helloimela approved these changes
looks good!

2021-05-18 06:09 UTC, mmexvr approved these changes

2021-05-18 09:47 UTC, vichtertz requested changes
Awesome work! I only have 2 comments:
- The cross should be grey-50 not white (it's my bad, I did it wrong in the design)
- When there is only a header, it looks like there is more space on the bottom than on the top. The header container should be 16px but there is extra space under (cf. screenshot), is it possible to fix it? 

![Screenshot 2021-05-18 at 11 34 37 (2)](https://user-images.githubusercontent.com/81550891/118628803-3f1d5e00-b7cd-11eb-8a80-ab83bf813350.png)

2021-05-19 09:43 UTC, vichtertz requested changes
The UI is perfect well done! Just one last thing, could you change these two namings in the Controls:
- Headline should be Header
- Subheadline should be Subheader

![Screenshot 2021-05-19 at 11 40 00](https://user-images.githubusercontent.com/81550891/118791616-29746b00-b897-11eb-86be-41bf89e3b164.png)

2021-05-20 09:29 UTC, helloimela commented
![image](https://user-images.githubusercontent.com/1199101/118954880-7c652580-b95e-11eb-97e5-c99001082959.png)

**The styling is a bit messed up in the website preview. You need to add "float:left" to the toast-headline span**
See image below

![image](https://user-images.githubusercontent.com/1199101/118955012-9b63b780-b95e-11eb-908b-6ef85a85e9b8.png)

2021-05-20 09:31 UTC, helloimela commented
![image](https://user-images.githubusercontent.com/1199101/118955158-bb937680-b95e-11eb-84ee-0a712c3fd5b4.png)

The link is affected by the website, you need to add class "sdds-toast-link" to the "a" element. And it is semantically wrong to have "a" inside "span". Change the structure to:

```
<div class="sdds-toast-body">
   <a href="#"  class="sdds-toast-link">Link example</a>
</div>
```

2021-05-21 07:14 UTC, merged