Feature - Banner component styling
scania-digital-design-system/sdds pull request #146
Opened 2021-05-19 12:42 UTC by mmexvr

**Describe pull-request**  
_Describe what the pull-request is about_
- New component banner
- Removed some unused code

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: AB#831

**How to test**  
_Add description how to test if possible_
Visit storybook either locally or with this preview link below
- Try different states
- Try different options, without prefix, subheadline and so on
- Screen size

**Additional context**  
_Add any other context about the pull-request here._

Demo has c-icon component to show a icon

2021-05-19 14:14 UTC, vichtertz requested changes
- Could you put a first capital letter by default on the Subheader text? 
![Screenshot 2021-05-19 at 15 52 21](https://user-images.githubusercontent.com/81550891/118824714-5d14bc80-b8ba-11eb-81df-98dd6fc82c4c.png)

- The icon should be filled icon 
![Screenshot 2021-05-19 at 16 08 54](https://user-images.githubusercontent.com/81550891/118827534-c0075300-b8bc-11eb-9187-0dbd664c4fec.png)

- Could you change the name in the Controls:
  Headline to Header
  Subheadline to Subheader 
(in order to use the same terminology as in the documentation)

![Screenshot 2021-05-19 at 16 11 11](https://user-images.githubusercontent.com/81550891/118827734-ee852e00-b8bc-11eb-9c72-1c8bea66c94e.png)

2021-05-20 06:20 UTC, mmexvr commented
> * Could you put a first capital letter by default on the Subheader text?
>   ![Screenshot 2021-05-19 at 15 52 21](https://user-images.githubusercontent.com/81550891/118824714-5d14bc80-b8ba-11eb-81df-98dd6fc82c4c.png)
> * The icon should be filled icon
>   ![Screenshot 2021-05-19 at 16 08 54](https://user-images.githubusercontent.com/81550891/118827534-c0075300-b8bc-11eb-9187-0dbd664c4fec.png)
> * Could you change the name in the Controls:
>   Headline to Header
>   Subheadline to Subheader
>   (in order to use the same terminology as in the documentation)
> 
> ![Screenshot 2021-05-19 at 16 11 11](https://user-images.githubusercontent.com/81550891/118827734-ee852e00-b8bc-11eb-9c72-1c8bea66c94e.png)

1. That is up to the user, but I will change in the demo that it is uppercase. I was just lazy :) 
3. I will change the naming for the controls and classes, agree it should match

2021-05-20 09:29 UTC, vichtertz approved these changes

2021-05-20 09:43 UTC, helloimela commented on components/src/components/banner/banner.scss
> +.#{$prefix}-banner-prefix {
In the future, this will contains icon, I assume the colour of the icons will follow the state. Maybe we can add the color to the prefix?
So the children will always inherit colour from this classes, and it will be flexible what is inside. In the demo we can use fill=currentColor in the rect svg. And if people want to add their own icon such as <i class=fa fa-book"></i>, it will also follow the colour from banner-prefix.

2021-05-20 15:21 UTC, mmexvr commented on components/src/components/banner/banner.scss
> +.#{$prefix}-banner-prefix {
Changed!

2021-05-21 07:12 UTC, helloimela approved these changes
Great work!

2021-05-21 08:01 UTC, helloimela approved these changes

2021-05-21 08:43 UTC, merged