AB#  Added spinner web component
scania-digital-design-system/sdds pull request #162
Opened 2021-06-15 08:28 UTC by kjec2f

**Describe pull-request**  
_Describe what the pull-request is about_
A spinner web component has added.
Added a web component to the demo/angular and demo/react folders.
**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #

**How to test**  
_Add description how to test if possible_
1. Go to... component/spinner
2. Check in...
3. Run ...

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

2021-06-17 08:43 UTC, helloimela commented on components/src/components/spinner/spinner.tsx
> +      const elems = [];
"elems" value has changed inside for loop. So let's use "let elems" instead of "const elems".

2021-06-17 08:49 UTC, helloimela commented
Merge master into the branch & fix conflict

2021-06-23 08:34 UTC, helloimela requested changes

2021-06-23 08:34 UTC, helloimela commented on theme/light/src/components/_spinner.scss
> +:root,
You need to import this file into sdds/theme/light/src/theme/sdds-theme.scss
@import '../components/spinner';

2021-06-28 08:19 UTC, kjec2f commented on theme/light/src/components/_spinner.scss
> +:root,
Imported

2021-06-28 10:34 UTC, helloimela requested changes

2021-06-28 10:34 UTC, helloimela commented on components/src/components/spinner/spinner.stories.js
> +  <div class="demo">
Need to add <sdds-theme></sdds-theme> in the stories to make it work in storybok preview

2021-06-28 11:21 UTC, kjec2f commented on components/src/components/spinner/spinner.stories.js
> +  <div class="demo">
Added.

2021-06-28 11:40 UTC, helloimela approved these changes

2021-06-28 11:48 UTC, merged