Added feature/slider-draft
scania-digital-design-system/sdds pull request #179
Opened 2021-08-18 22:16 UTC by kjec2f

**Describe pull-request**  
_Describe what the pull-request is about_
  Added slider-draft
**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #

**How to test**  
_Add description how to test if possible_
1. Go to storybook > component > slider
2. Desgin similar to "https://www.figma.com/proto/x0Lak62QgvbOuXW8bZFb9D/slider?page-id=80%3A379&node-id=80%3A578&viewport=677%2C691%2C0.11236094683408737&scaling=min-zoom"

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

2021-08-23 07:54 UTC, mmexvr commented
conflict

2021-09-01 08:18 UTC, mmexvr commented
I think there is an important prop missing, so if you have a range it should be possible to change the value it should be between. So if you have a price range for a product you might need to have bigger or smaller numbers.

So it should be possible to change the `min` and `max` attribute on the html to your need, because it might be needed for developers to change that attribute and use it. You might have a range between 2000-3000 and not 0-100 all the time.

Same with `value` attribute for the input element is important that they can access and use, they it should be able to set a default start value or not

`<input type="range" min="1" max="100" value="50" class="slider" id="myRange">`

2021-09-01 08:21 UTC, mmexvr commented on components/src/components/slider/slider.tsx
> +            min="1"
Should be able to customise this value

2021-09-01 08:21 UTC, mmexvr commented on components/src/components/slider/slider.tsx
> +            min="1"
Same with the other min and max on other examples

2021-09-01 08:25 UTC, mmexvr commented on components/src/components/slider/slider.tsx
> +          onKeyUp={(ev) => this.handleOnChangeRight(ev)}
Can we use just on change and not keyup, or is there a specific reason for keyup?

2021-09-01 08:27 UTC, mmexvr commented on components/src/components/slider/slider.tsx
> +    '--val': '20'
value should be default 0 and be customisable for the user, what the default value should start on

2021-09-01 08:27 UTC, mmexvr requested changes
Above comments :)

2021-09-02 09:39 UTC, alexlioliopoulos commented
We are also missing the hover state in the component.

2021-09-02 09:39 UTC, mmexvr commented
Can you seperate the examples so it has its own page in storybook, so duel point has one menu for example

2021-09-02 13:26 UTC, kjec2f commented on components/src/components/slider/slider.tsx
> +          onKeyUp={(ev) => this.handleOnChangeRight(ev)}
In order to detect the value and show error if the value is not correct before the user release

2021-09-06 15:47 UTC, alexlioliopoulos commented
From my point of view, great work!

2021-09-09 14:42 UTC, mmexvr commented
@alexlioliopoulos Should the slider be the size of where it is placed or is it always the same small size, can it be for example 6 col big?

2021-09-10 09:09 UTC, alexlioliopoulos commented
> @alexlioliopoulos Should the slider be the size of where it is placed or is it always the same size, 100px in this case, or can it be for example 6 col big instead?
> 
> I would assume there are cases where you want a bigger slider?

Great point! I suppose you are right, so we should give devs the option to change the width of it (but not the height).

2021-09-14 08:02 UTC, mmexvr commented
> > @alexlioliopoulos Should the slider be the size of where it is placed or is it always the same size, 100px in this case, or can it be for example 6 col big instead?
> > I would assume there are cases where you want a bigger slider?
> 
> Great point! I suppose you are right, so we should give devs the option to change the width of it (but not the height).

Yes! So instead of having a set width on the slider, remove that and let it grow with the parent element instead. So if the parent is 200px width, then the slider will be that.

2021-09-21 13:50 UTC, mmexvr approved these changes

2021-09-21 13:51 UTC, mmexvr commented
Looks good! 

Some options to add in the future:
- Add step option
- How the state should be when they are above each other

2021-09-21 13:51 UTC, merged