style(dropdown): restyling dropdown to fit along with other inputs
scania-digital-design-system/sdds pull request #286
Opened 2022-01-20 11:10 UTC by gaonita

**Describe pull-request**  
Restyle dropdown to fit along with other inputs
- No border radius on bottom edges
- Border only on the bottom 
- Border color on different states
  - default state: change to grey400
  - hover state: change to grey600
  - error state: change to semantic negative
  - focus state: change to blue400 and width 2px
  - active state: change to grey800
  - disabled state: no border 

Figma: https://www.figma.com/file/jZONFYFlckRROjSVPPu2DD/Dropdown-exploration?node-id=2%3A163

**Solving issue**  
Fixes: AB#1114

**How to test**  
1. Go to storybook dropdown example
2. Check the look of dropdown in different state

2022-01-20 13:46 UTC, alexlioliopoulos requested changes
Super good, nice job Gaon!
But since I need to find a reason why Scania is paying my salary, I have to comment on one small thing. 

I think that you are using grey-958 for both the "Select option" text, meaning the text that appears before user makes any selection, and for the options themselves.

According to design, the correct value is grey-700 for the "Choose an option" text, grey-900 for all the options, and grey-958 for the Option that the user has selected and is shown in the top part of the dropdown.

2022-01-20 13:56 UTC, mmexvr commented
on @alexlioliopoulos  comment 

- placeholder text is grey 700. Since it is a button it doens't have placeholder like textfield it will take the regular color.  Maybe have a class when a option is not picked that is using the placeholder color 
![image](https://user-images.githubusercontent.com/35451568/150348150-3243d684-b51c-4d97-b6b1-2effb3dedffc.png)

2022-01-21 13:26 UTC, gaonita commented
> 
this is 

> Another thing I noticed after having a look at the other variants:
> 
> The "label-inside" variant should be like this:
> 
> ![image](https://user-images.githubusercontent.com/76053160/150353028-7c0bfcc0-49a8-4830-9e0d-323f6c993414.png)
> 
> Now it's like this:
> 
> ![image](https://user-images.githubusercontent.com/76053160/150353083-002767ed-2e1c-4c85-b706-20a95a80b78e.png)
> 
> Meaning that in the current version, there is no label present, but we keep showing the "select option" text.

I see! then I will create a new ticket for this issue since it looks like more than restyling.

2022-01-21 13:37 UTC, gaonita commented
> Super good, nice job Gaon! But since I need to find a reason why Scania is paying my salary, I have to comment on one small thing.
> 
> I think that you are using grey-958 for both the "Select option" text, meaning the text that appears before user makes any selection, and for the options themselves.
> 
> According to design, the correct value is grey-700 for the "Choose an option" text, grey-900 for all the options, and grey-958 for the Option that the user has selected and is shown in the top part of the dropdown.

Fixed! please check it out again @alexlioliopoulos thank you for the tip @mmexvr !

2022-01-21 15:39 UTC, alexlioliopoulos approved these changes
Oh yes!

2022-01-21 16:12 UTC, mmexvr approved these changes

2022-01-21 20:10 UTC, merged