refactor(storybook): clean up unused addDecorator in storybook preview.js
scania-digital-design-system/sdds pull request #296
Opened 2022-01-28 08:24 UTC by gaonita

**Describe pull-request**  
Clean up unused import(`addDecorator, withThemes`) to properly use AWS amplify preview

**How to test**  
Check the preview from AWS amplify shows the current storybook example preview.

2022-01-31 09:00 UTC, areblk requested changes
Not sure if this change is the cause of the problems, but i noticed some weird differences between the amplfify and the netlify. I'd consider the first one a bug.

Screen images compare amplify (to the left) with netlify master (to the right)

**1. Docs-tab looks very different in amplify compared to netlify. The main difference is that code in "preview-boxes" doesn't render a preview, only showing code.**

![Docs look different-04](https://user-images.githubusercontent.com/97448894/151765012-d7d364e3-f510-424a-a437-c4c8cc70d4cd.PNG)
![Docs look different-01](https://user-images.githubusercontent.com/97448894/151765018-cb35c438-47e0-48f8-8c98-31d8f8730f1d.PNG)
![Docs look different-02](https://user-images.githubusercontent.com/97448894/151765023-4ca9ae35-ca16-4673-9e07-a6fe947ac85b.PNG)
![Docs look different-03](https://user-images.githubusercontent.com/97448894/151765027-c25c1721-eec0-4096-b11a-fee5d554d44d.PNG)

**2. The top part of Canvas-tab is shorter in amplify than in netlify.**

![Amplify preview shorter window-01](https://user-images.githubusercontent.com/97448894/151764980-b35b072c-e3a7-4425-92b6-b99f9f690a20.PNG)
![Amplify preview shorter window-02](https://user-images.githubusercontent.com/97448894/151764982-62a08f26-0dc3-4e8a-a2b6-88ecd9b58ca9.PNG)

2022-01-31 12:51 UTC, theJohnnyMe requested changes
Please check package.json in components level and main.js in .storybook - there are some imports left for storybook-addon-themes. Clean it, check if it works. I think after that we are good to go.

2022-01-31 13:00 UTC, theJohnnyMe commented
> Not sure if this change is the cause of the problems, but i noticed some weird differences between the amplfify and the netlify. I'd consider the first one a bug.
> 
> Screen images compare amplify (to the left) with netlify master (to the right)
> 
> **1. Docs-tab looks very different in amplify compared to netlify. The main difference is that code in "preview-boxes" doesn't render a preview, only showing code.**
> 
> ![Docs look different-04](https://user-images.githubusercontent.com/97448894/151765012-d7d364e3-f510-424a-a437-c4c8cc70d4cd.PNG) ![Docs look different-01](https://user-images.githubusercontent.com/97448894/151765018-cb35c438-47e0-48f8-8c98-31d8f8730f1d.PNG) ![Docs look different-02](https://user-images.githubusercontent.com/97448894/151765023-4ca9ae35-ca16-4673-9e07-a6fe947ac85b.PNG) ![Docs look different-03](https://user-images.githubusercontent.com/97448894/151765027-c25c1721-eec0-4096-b11a-fee5d554d44d.PNG)
> 
> **2. The top part of Canvas-tab is shorter in amplify than in netlify.**
> 
> ![Amplify preview shorter window-01](https://user-images.githubusercontent.com/97448894/151764980-b35b072c-e3a7-4425-92b6-b99f9f690a20.PNG) ![Amplify preview shorter window-02](https://user-images.githubusercontent.com/97448894/151764982-62a08f26-0dc3-4e8a-a2b6-88ecd9b58ca9.PNG)

Good catch @areblk! I have spent some time trying to find a workaround but I could not at the moment. I think there is something in the way we write our story file. Docs tab is not so much used, so far we rely only on Canvas one to make sure our components work OK. If you ask me, I would go with this bug as fully working Amplify is much more valuable to us compared to the Docs tab in Storybook. I checked the version on master branch - not many components have it done in a proper way anyway. Kind of: Is it a issue? - it is. Is it a blocker for us - no.

I would suggest reporting this as an issue in our backlog so we do not forget about it and we get back to it. Once again, nice catch really ;)

2022-01-31 13:47 UTC, gaonita commented
> Great catch indeed @areblk! I will try to make a preview using Netlify with this changes and compare them to be sure if this change caused the issue. 
But yes, I agree with you @theJohnnyMe. The docs addon is something we need to improve the way of use later anyway. I will clean up the package.json and let you know again :) 
Thank you for reviewing!

2022-01-31 16:28 UTC, gaonita commented
> 
That I checked before and it is without '@'. you can search the addons by names and see how you should import.  
 https://www.npmjs.com/package/storybook-addon-themes

2022-01-31 16:55 UTC, areblk commented
Last commit removed the option of changing theme per component. Now it's only possible to change background, but not the theme of the component (`on-white` or `on-grey´). Was this the intention?
![Theme-preview-removed](https://user-images.githubusercontent.com/97448894/151837491-a2ff84ce-ab98-49db-989e-e59e42b365cb.PNG)

2022-01-31 16:55 UTC, gaonita commented
Now I made a preview with netlify and the docs doesn't get properly rendered in there neither :(  might be the addon version is outdated... but like we said let's leave it as it is now and revisit later? I cleaned up the package.json @theJohnnyMe. Great work @areblk and thank you for making a report.

2022-01-31 17:02 UTC, gaonita commented
> Last commit removed the option of changing theme per component. Now it's only possible to change background, but not the theme of the component (`on-white` or `on-grey`). Was this the intention? ![Theme-preview-removed](https://user-images.githubusercontent.com/97448894/151837491-a2ff84ce-ab98-49db-989e-e59e42b365cb.PNG)
Oh maybe we are using that addon there! awesome you noticed @areblk! I'm adding it to the package again @theJohnnyMe  :D haha it's never ending task for me

2022-02-01 07:44 UTC, areblk commented
Theme preview is back, but it's in another place compared to main branch.

![f6d0804-theme-preview](https://user-images.githubusercontent.com/97448894/151930018-8dea2072-94db-4437-a3a9-000864f97a86.PNG)

![f6d0804-background-preview](https://user-images.githubusercontent.com/97448894/151930032-657d6608-af22-4efb-9483-cd0e19c6d70a.PNG)

2022-02-01 14:09 UTC, theJohnnyMe commented on components/package.json
> +    "storybook-addon-themes": "^6.1.0",
Good to have it next to each other, easy to spot all of it.

2022-02-01 14:12 UTC, theJohnnyMe approved these changes
There are things we can improve in Storybook, like the removal of the double theme icon, but that one seems to be appearing in old code too and hence is outside of the area of this branch.

Nice exploration and really nice work that simplifies our development. Keep on rocking Gaon! 
Thanks for finding time to work on it.

2022-02-01 15:05 UTC, areblk commented
OK with current state

2022-02-01 15:10 UTC, areblk approved these changes

2022-02-01 15:36 UTC, merged