Task 1381
scania-digital-design-system/sdds pull request #348
Opened 2022-04-05 10:56 UTC by victorscania

**Describe pull-request**  
Updated textarea and textfield with new functionality

**Solving issue**  
Fixes: AB#1381 and AB#1781

**How to test**  
Go to the generated storybook link
1781: Go to textarea, use the controler for rows and test if the size changes as you change rows.
1381: Go to textfield, change the controler for min width. resize the demo-contianer with inline with and se if the field cna shrink.

2022-04-05 14:02 UTC, areblk commented
**Text field nominwidth = true works as expected.**

**Suggested fixes for textarea**
I expected text area to have a "default" height that would apply when there is no row-attribute or when `rows`-argument is left blank, but it didn't. Suggestions for improvement:
1. When I delete the row-attribute in inspector, text area is slightly shorter than it used to be. 
2. I'd like to be able to leave `rows`-argument empty without getting an error message. (I've seen other components using the ternary operator to set value to default when there is no other value)

2022-04-06 09:40 UTC, gaonita approved these changes
confirmed it works as intended :)

2022-04-11 06:35 UTC, theJohnnyMe commented
I think your PR went to rebase hell, right? I will try to clean it up :)

2022-04-11 06:46 UTC, theJohnnyMe commented
@areblk and @victorscania  - I fixed the issue caused by rebase. Please double-check if everything looks ok. :)

2022-04-11 06:47 UTC, theJohnnyMe requested changes
Tiny thing from my side, others look good.

2022-04-11 06:47 UTC, theJohnnyMe commented on components/src/components/textfield/textfield.tsx
> +    console.log(this.nominwidth);
I just noticed this one, it cab be dropped, right?

2022-04-11 09:49 UTC, theJohnnyMe approved these changes
Great work! Looks good to me! Squash and merge it!  👍

2022-04-11 11:00 UTC, areblk approved these changes

2022-04-11 11:17 UTC, merged