Task 1874
scania-digital-design-system/sdds pull request #358
Opened 2022-04-14 14:54 UTC by victorscania

New webcomponent: datetime

this webcomponent uses the html-native datetime, date and time-picker
Fixes: AB#1874

**How to test**  
Open storybook and select the datetime component

**Additional context**  
This not a final PR, but intended to demo the component in its current state

2022-04-14 15:41 UTC, areblk commented
Tested on Edge and Windows

# Issues
Although most testing is done on datetime-local type, issues are also valid for type=date and type=time
1. **Basic.** (Only valid for Type=datetime-local). Input field is too short to show selected date and time. When clicked again, "PM" disappears and shows a somewhat correct value but without PM or AM.
![image](https://user-images.githubusercontent.com/97448894/163418673-fb1f0352-6b23-4570-a0d2-a17a969054ae.png)
2. **Disabled.** Icon should have the same color as text to make it more apparent that it's disabled https://digitaldesign.scania.com/components/datepicker/usage#states
![image](https://user-images.githubusercontent.com/97448894/163419289-60f81ef3-2bb3-4a68-ac0f-239a6f6700c0.png)
3. **Labels.** Cannot see where the label goes. By the inspection tool, Storybook seem to pass it to the DOM but I cannot see it.
![image](https://user-images.githubusercontent.com/97448894/163419854-0c4353ca-7b8f-4929-9e11-4ad5d2f7b4e5.png)
4. **Labels > Label inside.** Label is displaced when no date is selected. (Label looks OK when date is selected)
![image](https://user-images.githubusercontent.com/97448894/163420230-cd8927a9-c8c9-46e5-9bfc-e0d70c3cc7a0.png)
5. **Helper.** Helper text works in default state, but disappears when ex. label is added inside. Shadow DOM looks a bit corrupt
![image](https://user-images.githubusercontent.com/97448894/163420961-054608a6-4c31-4ea0-a989-cbbfe9cb10a8.png)
![image](https://user-images.githubusercontent.com/97448894/163421109-271c1b0b-f7a2-412d-a0f9-55f8e8e36db5.png)
6. **State > Error state.** Should have an icon before Helper text. (See how it's done in the Dropdown component https://deploy-preview-358--sdds-storybook.netlify.app/?path=/story/component-dropdown--helper&args=state:error)
7. **State > Error state.** Calendar/clock icon should be red when in error state https://digitaldesign.scania.com/components/datepicker/usage#states.
8. **Icon.** Not able to see where icon goes.
![image](https://user-images.githubusercontent.com/97448894/163422210-60a967bf-5f20-4ff8-bf35-fb86716d9145.png)

# Note
9. Format according to SDDS should be YYYY-MM-DD, and preferably also 24H format on time, but I find no easy access evidence that it's possible using the native one.

2022-04-19 08:05 UTC, theJohnnyMe requested changes

2022-04-19 08:05 UTC, theJohnnyMe commented on components/src/components/datetime/datetime.scss
> +      //background-color: red;
Maybe can be removed as no rule is assigned?

2022-04-19 08:05 UTC, theJohnnyMe commented on components/src/components/datetime/datetime.scss
> +      //background-color: green;
Same here.

2022-04-19 08:05 UTC, theJohnnyMe commented on components/src/components/datetime/datetime.scss
> +      //background-color: blue;
Same here.

2022-04-19 08:05 UTC, theJohnnyMe commented on components/src/components/datetime/datetime.tsx
> +  @Listen('focus')
Nice!

2022-04-19 08:05 UTC, theJohnnyMe commented on components/src/components/datetime/datetime.tsx
> +  @Listen('focusout')
Nice!

2022-04-19 08:08 UTC, theJohnnyMe commented
![overlapping](https://user-images.githubusercontent.com/17004063/163955873-866579a0-d1ce-45fc-b72d-c01d126bbc88.png)

Placeholder and label overlapping. I think Annika mentions similar/same issue under no.4.

2022-04-19 08:15 UTC, theJohnnyMe commented
1. See if it is possible to add a prop for min & max date so the user can specify that too.

2. Another useful thing is to present the selected date&time as seconds in the attribute for internal calculation.
It could look like:
`<sdds-datepicker value="2017-06-01" numeric-value="1496275200000" ... > `

2022-04-19 11:17 UTC, alexlioliopoulos commented
@victorscania What are your feelings about the issues identified by Annika and Johnny? I mean, is there anyone that would require long time to be fixed, hence we should consider if it should be prioritized or not? Let me know!
But anyway, as always, prio #1 are things that look broken. In this case the "label-inside" variant. Styling problems or extra functionality come after that.

2022-04-20 14:30 UTC, areblk commented
# Fixed
- (2) Icon is grey when disabled

# Status
Everything else as before, except for
- Icon prop, because that has been removed
- Label inside, has also been removed

My opinion on what's to be considered broken and therefore should be fixed are things having to do with labels and error helper text (3, 4, 6). I'd prioritize nr.3 (making label text visible) because all of my other points, including 4 and 6, can be solved with workarounds in consumer apps.

2022-04-20 21:27 UTC, alexlioliopoulos commented
> 

I would say let's prioritize 3 & 4. If our users are using the label-inside textfield in a form, they need to have the equivalent for the dropdown. 

Another thing to work on, is to create a "small" variant that has a height of 40px (large is 56px tall, medium is 48px tall).

2022-05-10 11:23 UTC, areblk approved these changes

2022-05-10 11:48 UTC, merged