feat: (container) simple container
scania-digital-design-system/sdds pull request #366
Opened 2022-04-28 10:22 UTC by victorscania

**Describe pull-request**  
Added a new simple container component

**Solving issue**  
Fixes: AB#1728

**How to test**  
Look at the container component in storybook

2022-04-28 11:51 UTC, areblk commented
1. Please remove demo-classes in story so it's easier to test the component, i.e. avoiding false results.

- Not sure if we should have **dark-theme** variants since no other components are available as such, meaning that they can't be used anyway. For example: sdds-body-01 styled paragraphs are impossible to read on a dark-theme component because there's style for it. My suggestion is to remove dark-themes completely, alternately tag them as alpha so they stay in storybook but not showcase them on website or mention them in release notes. What do you say @theJohnnyMe ?
- **Contradictory requirements for padding.** Azure task say 8px padding, but SDDS docs say 16px. Component has 16px padding. I think the Azure task is a mistake, but might be worth controlling with someone.

2022-05-10 07:31 UTC, areblk requested changes
final removal of dark-theme variants in storybook to keep stories clean

2022-05-10 07:31 UTC, areblk commented on components/src/components/container/container.stories.js
> +        options: ['onwhite', 'ongrey', 'ongrey958', 'ongrey900'],
ongrey958 and ongrey900 should be removed

2022-05-10 07:31 UTC, areblk commented on components/src/components/container/container.stories.js
> +          ongrey958: 'On grey-958',
should be removed

2022-05-10 07:31 UTC, areblk commented on components/src/components/container/container.stories.js
> +          ongrey900: 'On grey-900',
should be removed

2022-05-10 07:31 UTC, areblk commented on components/src/components/container/container.stories.js
> +  .sdds-demo-containerbox-ongrey958 { background-color: var(--sdds-grey-958); color: #fff; }
remove

2022-05-10 07:31 UTC, areblk commented on components/src/components/container/container.stories.js
> +  .sdds-demo-containerbox-ongrey900 { background-color: var(--sdds-grey-900); color: #fff; }
remove

2022-05-11 12:42 UTC, theJohnnyMe commented on components/src/components/container/container.stories.js
> +        options: ['onwhite', 'ongrey', 'ongrey958', 'ongrey900'],
I agree with Annika, remove it from Storybook controls, but keep logic and CSS for it - we might need it in the future. 
The reason for removing it from Storybook is not to mislead users so they think we have a dark theme ready.

2022-05-11 12:55 UTC, theJohnnyMe requested changes

2022-05-11 12:55 UTC, theJohnnyMe commented on components/src/components/container/container.scss
> +.sdds-containerbox {
We just decided to rename this one to "sdds-block" instead as container is already taken and containerbox is too long... Sorry for bringing this up in late stage, but just rename all containerbox to the block.

2022-05-11 12:57 UTC, theJohnnyMe commented
PS: Check your code editor, it seems like it changes all single quotes to double ones on save. In repo, Prettier config is set to use single quotes.

2022-05-12 09:34 UTC, areblk requested changes
- Some storybook things for dark theme is still there. It seems it's not enough to remove story, but also need to remove label values for that control
![image](https://user-images.githubusercontent.com/97448894/168040128-6fdcff4b-0e22-4f19-902f-28276cb1a9be.png)
- Some automatic formatting(?) changed single quotes to double quotes in .scss-files. Please check :-)

2022-05-12 09:34 UTC, areblk commented on components/src/components/block/block.stories.js
> +          ongrey958: 'On grey-958',
please remove control since it's not ready

2022-05-12 09:34 UTC, areblk commented on components/src/components/block/block.stories.js
> +          ongrey900: 'On grey-900',
please remove control since it's not ready

2022-05-16 08:38 UTC, areblk approved these changes

2022-05-16 09:24 UTC, theJohnnyMe commented
Due to merges, merge conflicts and old commit showing up I did this one PR with cherry-picked commits: [Block component PR](https://github.com/scania-digital-design-system/sdds/pull/371)

2022-05-16 09:24 UTC, closed without merging