feat: chips & message components
scania-digital-design-system/sdds pull request #381
Opened 2022-06-02 11:33 UTC by victorscania

**Describe pull-request**  
Two new components. Chips and Messages

**Solving issue**  
Fixes: [AB#1730](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1730) and [AB#1904](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/1904)

**How to test**  
1. Go to the storybook
2. check chips, go thru the storie and see if they are correct
3. check messages, check the stories, and use the controls to se if you can create all variants.

2022-06-03 05:02 UTC, albinscania approved these changes
Looks good and works great.
It's weird that your commits however seem to remove quotes and add double quotes instead... :)

2022-06-03 07:25 UTC, gaonita approved these changes
both work great! I just found some tiny stuff, left some comments here :)

and yeah like Albin says it looks like Victor's prettier(?) and Johnny's eslint(?) fighting against with single/double quotation mark 😆

2022-06-03 07:25 UTC, gaonita commented on components/src/components/message/message.scss
> +        background-color: #ff2340;
these semantic colors as well, we can use semantic variables? 🚥

2022-06-03 07:25 UTC, gaonita commented on components/src/components/message/message.scss
> +    //left: 20px;
found commented out lines 😬

2022-06-03 07:25 UTC, gaonita commented on components/src/components/message/message.scss
> +    background-color: #2b70d3;
can this color be a variable like '--sdds-blue-400' maybe?

2022-06-03 07:37 UTC, theJohnnyMe commented
> Looks good and works great. It's weird that your commits however seem to remove quotes and add double quotes instead... :)

I will check the settings on my machine. Something is off for sure :D

2022-06-03 08:25 UTC, theJohnnyMe requested changes

2022-06-03 08:25 UTC, theJohnnyMe commented on components/src/components/message/message.stories.js
> +  const iconHtml = `
I suggest turning this SVG to a button holding SVG that has a "pointer" cursor when hovered over:

![Screenshot 2022-06-03 at 09 44 45](https://user-images.githubusercontent.com/17004063/171816876-a71dd5c9-e8c8-4e3a-be46-51b3bf88cfb5.png)

That way we will deliver a ready solution so users can easily attach a function to that button.

2022-06-03 08:28 UTC, theJohnnyMe requested changes

2022-06-03 08:28 UTC, theJohnnyMe commented on components/src/components/chips/chips.stories.js
> +  const iconSvg = `
Maybe this could be also a button with SVG in it, same as in the message component to easily attach function on it?

2022-06-07 10:48 UTC, victorscania commented on components/src/components/message/message.stories.js
> +  const iconHtml = `
I dont think that is suppose to be a button rather just an icon. I just used the X icon as an example. Maybe replace it with something else tho, to avoid confusion.

2022-06-07 10:49 UTC, victorscania commented on components/src/components/chips/chips.stories.js
> +  const iconSvg = `
same thing here. its just an icon. I really should have used another icon ;)

2022-06-08 14:08 UTC, theJohnnyMe commented on components/src/components/message/message.stories.js
> +  const iconHtml = `
Aha, ok, I got it now. Yeah, "x" confused me. :D 
I checked with @charlottelorensson and each type of message has a dedicated icon. For example, success/positive one has a checkmark there. Can you please check with her which icons are associated with which type and fix it in the example in Storybook?

2022-06-08 14:11 UTC, theJohnnyMe commented on components/src/components/chips/chips.stories.js
> +  const iconSvg = `
All good here then ;) I agree with you, maybe, just as a suggestion try to add an example with "Like" as text and a "Hearth" icon next to it to avoid confussion. I feel others will end up in similar trap like I did hehe

2022-06-09 13:39 UTC, theJohnnyMe reviewed
@victorscania Looks good to me, thanks for sorting icons confusion ;)
One thing is to check Gaon's comments, maybe you missed them, I think it is a quick fix.

2022-06-10 10:13 UTC, alexlioliopoulos requested changes
They both look great!

I only have one request: 
We should add a small variant for the chips. The large one is 32px high and the small one is 24px high. Otherwise they are identical.

2022-06-13 08:04 UTC, gaonita approved these changes
LGTM 👍🏻

2022-06-13 14:17 UTC, alexlioliopoulos approved these changes

2022-06-15 11:13 UTC, merged