Dropdown fixes sprint 36
scania-digital-design-system/sdds pull request #406
Opened 2022-07-11 11:57 UTC by EmelieLitwin

**Describe pull-request**  
Improvements on the dropdown component.
- Added arrow navigation
- Fixed disable option bug
- Increased z-index to fix overlapping  issues
- Closing dropdown when clicking on open dropdown
- Fixed bugs for inside label (Long labels doesn't align with selected option and overflows)

**Solving issue**  
AB#1994 
AB#1997 
AB#2017 
AB#2014

**How to test**  
1. Open storybook
2. Check if arrow navigation works on dropdown component (not on disabled version)
3. Try closing it by clicking on it
4. Try long labels in the inside label option and see if it works correctly

2022-07-11 12:33 UTC, alexlioliopoulos commented
Nice! Super fast as well! 

I have nothing to comment on when it comes to the "collapse when clicking outside", "disabled state" and "z-index issue". Although the latter one needs to be tested in contexts that coexist with other elements to make sure it works.

Regarding the "up and down arrows", it works great, however it now does not have a hover state, rather than goes to the focused state while hovering (meaning that you get the blue outline which is the focused state visual hint while hovering, instead of the plain background colour change).

Some further comments for the dropdown, that don't have to do with the work you have done though, but since you are touching upon it, perhaps you might have ideas how to tackle them:

1. There are multiple styling differences between the component as it is designed, and the one in code. 

![image](https://user-images.githubusercontent.com/76053160/178264699-8c8599c5-d8fa-421c-ad01-916f018ef0ca.png)

The padding to the left is 16px in design but 20px in code. Also, as can be seen in the image above, the spacings of the elements within the component (label, text etc) are different in design and in code.

2. Sometimes, part of the menu list is not accessible to the users when inside blocks or divs or or. For instance the image below

![image](https://user-images.githubusercontent.com/76053160/178265053-107f6e38-a540-4f6c-9889-21b0d7519c31.png)

I cannot select the 3-4 first menu items while in my laptop, unless I change the browser zoom to 60%, which is a hack that few people would do though. Is that something that we could somehow solve?

2022-07-11 16:42 UTC, theJohnnyMe commented on components/src/components/dropdown/_dropdown-core.scss
> +  @include type-style("detail-02");
We can check your IDE for loading settings for ESLint and Prettier. It should be a single quote. Not a biggy.

2022-07-11 16:52 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown.scss
> +  .sdds-dropdown-toggle--selected:not(:focus) {
Why is :not(:focus) needed for?

2022-07-11 16:52 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown.tsx
> +  @Listen('keydown')
Really neat solution, nice work!

2022-07-11 16:52 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown.tsx
> +            <span class="sdds-dropdown-label">
I guess switching to span as it brings fewer styles to overwrite?

2022-07-11 17:02 UTC, EmelieLitwin commented on components/src/components/dropdown/dropdown.tsx
> +            <span class="sdds-dropdown-label">
Yeah and semantically it didn't feel great to have a div in a button :)

2022-07-11 17:04 UTC, EmelieLitwin commented on components/src/components/dropdown/dropdown.scss
> +  .sdds-dropdown-toggle--selected:not(:focus) {
I had a reason when I wrote it but maybe it's not needed anymore. I'm going to investigate.

2022-07-12 09:44 UTC, theJohnnyMe commented
@EmelieLitwin couple of things I think need some attention:
1. When in Dropdown with the selected option "lable-inside", I think the color of the selected text has to change, a bit darker -  I think Alex mentioned it too.
2. Check disabled state and label color for "lable-inside" variation.
3. Check the disabled state of filter variation, it seems like it does not work.

2022-07-14 09:28 UTC, theJohnnyMe approved these changes

2022-07-14 09:51 UTC, alexlioliopoulos commented
Great work! Some last minor feedback from my side (plus I think it would be good to add me or a designer as a reviewer as well, for the visual parts):

![image](https://user-images.githubusercontent.com/76053160/178955157-c3d4c567-d763-4576-8348-eaf5c639d353.png)

The no-label and inside variants have the text placed a little bit differently, as can be seen in the image above. When inspecting it seems like it has to do with the wrappers (i might be using a wrong term), but seems like a quick fix.

2022-07-14 11:05 UTC, alexlioliopoulos requested changes
Great work @EmelieLitwin ! Some last minor feedback from my side (plus I think it would be good to add me or a designer as a reviewer as well, for the visual parts):

![image](https://user-images.githubusercontent.com/76053160/178955157-c3d4c567-d763-4576-8348-eaf5c639d353.png)

The no-label and inside variants have the text placed a little bit differently, as can be seen in the image above. When inspecting it seems like it has to do with the wrappers (i might be using a wrong term), but seems like a quick fix.

2022-07-15 11:00 UTC, alexlioliopoulos approved these changes
Lovely!

2022-07-15 11:59 UTC, merged