New Slider component (Task 1903)
scania-digital-design-system/sdds pull request #422
Opened 2022-08-24 16:09 UTC by albinscania

**Describe pull-request**  
Created SLIDER component according to design here:
https://www.figma.com/file/yOgycQh7fsEtBz77CyUtRk/Slider?node-id=69%3A7716

NOTE: Dark Theme is not yet implemented.

Fixes: #1903

**How to test**  
Checkout this branch and navigate to the slider-component. The old ALPHA-one is still there for legacy reasons but we can probably remove that this will be merged.

2022-08-24 22:07 UTC, alexlioliopoulos commented
I will check it again tomorrow more thoroughly, but it seems to be splendid!

I only have a weird comment: it seems that for some reason you need to scroll to see the slider component in storybook

![image](https://user-images.githubusercontent.com/76053160/186532190-7f4b61ae-72bd-46a5-90c3-c87685e164ee.png)

2022-08-25 13:38 UTC, theJohnnyMe requested changes

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/components/slider/slider.scss
> +        padding-left: 0;
To keep it neat, maybe it is better to use padding: 18px 18px 18px 0; ? 
Same goes for line 48.

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/components/slider/slider.scss
> +        box-shadow: inset 0 -1px 0 #cdd1db;
Do we have these colors as CSS variables?
The same goes for lines 88 and 92. 
Please check.

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/components/slider/slider.scss
> +          opacity: 0.16 !important;
Justo noticed this one. Is there a way to avoid usage of important here or it complicates stuff too much?

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/components/slider/slider.tsx
> +  @Prop() max = '100';
Please provide a comment above each prop on what it does in a form /** Test 123 */ - it ends up in an autogenerated readme which is super useful for other developers.

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/components/slider/slider.tsx
> +      /*const step =
I guess this can be removed.

2022-08-25 13:38 UTC, theJohnnyMe commented on components/src/alpha/slider/slider.tsx
>  @Component({
Just delete this entire component folder and files, it is not needed anymore. 
Glad that you are careful though.

2022-08-25 13:45 UTC, theJohnnyMe commented on components/src/components/slider/slider.stories.js
> +    .storybook-slider-wrapper {
This one gives false positives in visual testing. A component might need some padding-top / margin-top to display correctly. Let me show you in devCheckIn.

2022-08-25 13:50 UTC, theJohnnyMe commented on components/src/components/slider/slider.stories.js
> +      name: 'Show dividers',
Question: Should we count in start & end dividers too? When you have 3 as the value, it is actually 5. Just to avoid confusion.

2022-08-25 13:53 UTC, theJohnnyMe commented on components/src/components/slider/slider.stories.js
> +      name: 'Show dividers',
Or should we simply say how many sections you want, meaning if you want 0,10,20,30... to 100, you need to say I want 10 sections. Just thinking was it easier to understand for the end user?

2022-08-25 13:56 UTC, theJohnnyMe requested changes

2022-08-25 13:56 UTC, theJohnnyMe commented on components/src/components/slider/slider.stories.js
> +      name: 'Small',
Maybe name it "Smaller thumb" or "Small indicator" as the only the size of that particle changes, not an entire component.

2022-08-25 18:23 UTC, albinscania commented on components/src/components/slider/slider.scss
> +      /* width: 16px;
Removed all comments!

2022-08-25 18:24 UTC, albinscania commented on components/src/components/slider/slider.tsx
> +  @Prop() label = '';
Added prop descriptions!

2022-08-25 18:24 UTC, albinscania commented on components/src/components/slider/slider.tsx
> +  wrapperElement: HTMLElement = null;
Added @element() decorator for conformity!

2022-08-25 18:24 UTC, albinscania commented on components/src/components/slider/slider.scss
> +        box-shadow: inset 0 -1px 0 #cdd1db;
@theJohnnyMe Yes we did! Updated!

2022-08-25 18:25 UTC, albinscania commented on components/src/components/slider/slider.scss
> +          opacity: 0.16 !important;
I think it gets slightly messier to move that block of css (which would be needed), into the nested spot.
It's the only !important in the whole .scss though ;)

2022-08-25 18:25 UTC, albinscania commented on components/src/components/slider/slider.tsx
> +  @Prop() max = '100';
Fixed

2022-08-25 18:25 UTC, albinscania commented on components/src/components/slider/slider.tsx
> +      /*const step =
It mostly def. can! fixed.

2022-08-25 18:26 UTC, albinscania commented on components/src/alpha/slider/slider.tsx
>  @Component({
Deleted!

2022-08-25 18:26 UTC, albinscania commented on components/src/components/slider/slider.stories.js
> +    .storybook-slider-wrapper {
I updated the container (still have some style there though, but it makes more sense).
Also added a sensible default top-padding to the component itself like we discussed.

2022-08-25 18:27 UTC, albinscania commented on components/src/components/slider/slider.stories.js
> +      name: 'Show dividers',
I think it kind of makes sense the way it is now (not counting start and end). Also, if a user gets it wrong the first time it should be kind of clear what they need to to imho.

I'll hold on to this for a while until we talked about renaming them and stuff.

2022-08-25 18:28 UTC, albinscania commented on components/src/components/slider/slider.stories.js
> +      name: 'Small',
I'll let Matylda or Alex decide this. Works for me to call the prop "small-thumb" instead if we want.

2022-08-30 06:53 UTC, theJohnnyMe commented on components/src/components/slider/slider.tsx
> +  @Prop() label = '';
Awesome! ;)

2022-08-30 06:53 UTC, theJohnnyMe commented on components/src/components/slider/slider.scss
> +        box-shadow: inset 0 -1px 0 #cdd1db;
Great!

2022-08-30 06:54 UTC, theJohnnyMe commented on components/src/components/slider/slider.scss
> +          opacity: 0.16 !important;
Sure, no problem, it is just to double check ;)

2022-08-30 06:54 UTC, theJohnnyMe commented on components/src/components/slider/slider.stories.js
> +    .storybook-slider-wrapper {
Great!

2022-08-30 06:58 UTC, theJohnnyMe commented
Check if snapping can get of divider, for example in this one: 25, 50, 75, 100...
![Screenshot 2022-08-30 at 08 57 09](https://user-images.githubusercontent.com/17004063/187370629-e191a9ec-37c2-4e16-b1b8-04e324f5156c.png)

2022-08-30 07:01 UTC, EmelieLitwin commented
Amazing job!
I tried the "snapping" and it snaps to 24, 49, 74 etc for me (or at least that's what the tooltip say)

2022-08-30 09:19 UTC, EmelieLitwin approved these changes
Looks good to me 😍

2022-08-30 12:57 UTC, theJohnnyMe approved these changes
Works like a charm!

Lets rebase this one together before merge to resolve old code jumping in or merge conflicts :)

2022-08-31 08:43 UTC, merged