Created Canvas Popover Component (Task 2042)
scania-digital-design-system/sdds pull request #423
Opened 2022-08-25 11:45 UTC by albinscania

**Describe pull-request**  
A first version of the popover canvas component.

**Solving issue**  
Fixes: #2042

**How to test**  
Checkout the branch and navigate to the popover component.
Click the little "kebab"-icon to trigger the canvas popup, which has some sample content.

2022-08-25 12:17 UTC, alexlioliopoulos approved these changes
Another great one, thanks Albin! 

Just a question: is there a difference between bottom and bottom-start? They seem to be giving the exact same placement for me.

2022-08-25 18:15 UTC, albinscania commented
@alexlioliopoulos yeah, that's a good point. I used the same ones from "tooltip", but I also can't really see the difference here. I can clean it up a bit!

2022-08-30 13:10 UTC, theJohnnyMe requested changes

2022-08-30 13:10 UTC, theJohnnyMe commented on components/src/components/popoverCanvas/popovercanvas.tsx
> +      <div
This is a great candidate to use Host tag instead as then you do not need to use reference.

2022-08-30 13:10 UTC, theJohnnyMe commented on components/src/components/popoverCanvas/popovercanvas.tsx
> +  /** The CSS-selector that will trigger this Popover Canvas */
Great job with adding comments ;)

2022-08-30 13:10 UTC, theJohnnyMe commented on components/src/components/popoverCanvas/popovercanvas.tsx
> +  tag: 'sdds-popover-canvas',
Not aimed for this line, but for naming files and folder. I would suggest renaming the folder and files to one that uses the hyphen: popover-canvas, popover-canvas.scss... Just to keep consistent with side-menu, code-sample, radio-button etc...

2022-08-31 08:27 UTC, theJohnnyMe approved these changes
Looks good to me.

2022-08-31 08:55 UTC, merged