New component: Popover Menu
scania-digital-design-system/sdds pull request #424
Opened 2022-08-26 08:09 UTC by albinscania

**Describe pull-request**  
A new component in the form of a Popover Menu, based on core-code from the popover canvas component.

**Solving issue**  
Fixes: #2043

**How to test**  
Go to the netlify link or checkout the branch, and browse to the PopoverMenu component. Click the kebab-dots to see it in action, both with and without icon.

NOTE.
@alexlioliopoulos I couldn't find the "hover"-color in the figma (only in the prototype) so if you could give me the exact sdds-color for that I will update asap.

2022-08-26 09:29 UTC, alexlioliopoulos commented
It is grey-100! 

(sdds-library in Figma is usually the source of truth when in doubt)
![image](https://user-images.githubusercontent.com/76053160/186873826-c12fd2d1-804e-4677-ad9c-69620847c7f2.png)

2022-08-26 09:32 UTC, alexlioliopoulos commented
Looks great as Matylda said! 

It is a tradition though to have at least one question in every PR so I won't break it here :D 

It might not have been clear on the task itself, but the idea was that either have icons for all items, or for none of them. Could we set it to be like that? Also we want devs using this to be able to add a divider wherever they want. Is it flexible like that?

2022-08-26 13:39 UTC, albinscania commented
@alexlioliopoulos Ah I see... I guess I can add something like an "with-icon" class and then just indent the text where they choose not to add an icon? (even if that's against the design).

And yes, dividers can be added anywhere :)

2022-08-26 13:53 UTC, alexlioliopoulos commented
> 

That would be an even greater solution - let's go with it if it is easy to make!

2022-08-30 13:20 UTC, theJohnnyMe requested changes

2022-08-30 13:20 UTC, theJohnnyMe commented on components/src/components/popoverMenu/popovermenu.scss
> +      display: block;
As one on 40 is flex, this one can be removed.

2022-08-30 13:20 UTC, theJohnnyMe commented on components/src/components/popoverMenu/popovermenu.scss
> +  background-color: #fff;
Not a biggy but could be var(--sdds-white)...

2022-08-30 13:20 UTC, theJohnnyMe commented on components/src/components/popoverMenu/popovermenu.tsx
> +        ref={(el) => (this.popoverMenuElement = el as HTMLElement)}
As in popover canvas, this is a good chance to use Host :)

2022-08-30 13:20 UTC, theJohnnyMe commented on components/src/components/popoverMenu/popovermenu.tsx
> +  styleUrl: 'popovermenu.scss',
as in popover canvas, see if folder name and files in can be renamed to popover-menu, popover-menu.scss etc... just to align with rest of "two-words" components...

2022-08-30 13:20 UTC, theJohnnyMe commented on components/src/components/popoverMenu/popovermenu.stories.js
> +      name: 'withIcons',
In the version of the story, I checked there were no icons showing when this one was true. Please check.

2022-08-31 08:28 UTC, theJohnnyMe approved these changes
Looks good to me.

2022-08-31 09:01 UTC, merged