fix: (checkbox/radio) adjusted click-area to cover hover effect
scania-digital-design-system/sdds pull request #432
Opened 2022-09-01 09:21 UTC by victorscania

**Describe pull-request**  
adjusted click-area to cover hover effect

**Solving issue**  
Fixes: AB#2206 and AB#2207

**How to test**  
Open storybook and check out the checkbox and radio button component. test if the click area includes the hover effect.

2022-09-01 09:30 UTC, alexlioliopoulos approved these changes

2022-09-02 06:40 UTC, alexlioliopoulos approved these changes
Looking good!

2022-09-02 09:08 UTC, theJohnnyMe requested changes

2022-09-02 09:08 UTC, theJohnnyMe commented on components/src/components/checkbox/checkbox.scss
> +@import "../../helpers/style-helpers.scss";
Please check with @albinscania to see if some settings in VS have to be changed or something else in order to avoid changing single to double quotes.

2022-09-02 09:08 UTC, theJohnnyMe commented on components/src/components/checkbox/checkbox.scss
> +    //background-color: var(--sdds-checkbox-interaction-02);
Delete it if not needed.

2022-09-02 09:08 UTC, theJohnnyMe commented on components/src/components/radio-button/radio-button.scss
> +    //background-color: var(--sdds-radio-button-interaction-02);
Delete it if not needed.

2022-09-05 10:36 UTC, albinscania approved these changes
Let's discuss prettier-config on our next devmeeting. otherwise, looks good and solves the problem.

2022-09-05 10:36 UTC, albinscania commented on components/src/components/checkbox/checkbox.scss
> +@import "../../helpers/style-helpers.scss";
Hmm yeah, I think we should discuss this a bit on the next dev-meeting. Seems like our prettier configs are not in sync? which is weird, since they should be.

2022-09-05 14:23 UTC, theJohnnyMe approved these changes
Looks good to me! :)

2022-09-14 11:26 UTC, merged