feat(dropdown): new multiselect type  #506
scania-digital-design-system/sdds pull request #439
Opened 2022-09-08 11:33 UTC by EmelieLitwin

**Describe pull-request**  
A new multiselect variation of the dropdown component

**Solving issue**  
AB#506 Build component - Multiselect

**How to test**  
_Add description how to test if possible_
1. Go to storybook and test functionality

2022-09-08 13:31 UTC, alexlioliopoulos requested changes
Amazing work! I only have one small comment:

![image](https://user-images.githubusercontent.com/76053160/189135011-8d2a254b-2260-4a2b-9217-6b33dc6e51a7.png)

I think there is a weird white line on the left side of the component, which only shows when a selection has been made. Would it be possible to remove it?

Update:

We are also missing 1) the two label variants, and 2) the read-only version.

As stated in our chat, it is not a hard requirement for this sprint. We can push something out now, and add the extra things next time.

2022-09-12 07:02 UTC, alexlioliopoulos commented
> Amazing work! I only have one small comment:
> 
> ![image](https://user-images.githubusercontent.com/76053160/189135011-8d2a254b-2260-4a2b-9217-6b33dc6e51a7.png)
> 
> I think there is a weird white line on the left side of the component, which only shows when a selection has been made. Would it be possible to remove it?
> 
> **Update:**
> 
> We are also missing 1) **the two label variants**, and 2) **the read-only version**.
> 
> As stated in our chat, it is not a hard requirement for this sprint. We can push something out now, and add the extra things next time.

I played around a bit and it seems that the white stripe appears only in some zoom levels. 125, 90, 75 are where the issue happens; in all other zoom levels it does not show up.

2022-09-13 08:08 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown-filter.tsx
> +  @Prop() size: string = 'lg';
Nice!

2022-09-13 08:45 UTC, ahujamoh commented on components/src/components/dropdown/dropdown-filter.tsx
> +  @Prop() size: string = 'lg';
it could be 

@Prop() size: 'sm' | 'md' | 'lg' = 'lg';

keeping the size property strongly typed (as we know these will be the expected types)

2022-09-13 08:49 UTC, ahujamoh commented on components/src/components/dropdown/dropdown.tsx
> +  @Prop() size: string = 'lg';
(same comment as before)

it could be

@prop() size: 'sm' | 'md' | 'lg' = 'lg';

keeping the size property strongly typed (as we know these will be the expected types)

2022-09-13 08:54 UTC, ahujamoh commented on components/src/components/dropdown/dropdown.tsx
> +      this.optionValues.push(this.listItemArray[i].value);
We can use imperative style instead of being declarative, would make it easy to read.

```
this.listItemArray.map((listItem) => {
  this.optionValues.push(listItem.value);
  this.optionLabels.push(listItem.label);
});
```

2022-09-13 08:57 UTC, EmelieLitwin commented on components/src/components/dropdown/dropdown-filter.tsx
> +  @Prop() size: string = 'lg';
Good point! Thank you for the feedback Mohit! 😄

2022-09-13 09:00 UTC, ahujamoh commented on components/src/components/dropdown/dropdown.tsx
> +    this.open ? this.open : !this.open;
may be i am wrong, but shouldn't this be assigned to `this.open`?

2022-09-13 09:01 UTC, ahujamoh reviewed
made some suggestion

2022-09-13 11:35 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown.tsx
> +    if (this.size === 'small') {
Nice!

2022-09-19 12:57 UTC, alexlioliopoulos requested changes
Something seems to be off now, it was not like that before. Check here:

![image](https://user-images.githubusercontent.com/76053160/191022441-bee5abde-70c7-43cf-9ed9-2650a97f76dc.png)

Also, not sure if it was like that before, but at least now when you select an option, the dropdown collapses and if you want to select more, you need to expand it again. Should it be like that?

2022-09-19 14:03 UTC, EmelieLitwin commented
> Something seems to be off now, it was not like that before. Check here:
> 
> ![image](https://user-images.githubusercontent.com/76053160/191022441-bee5abde-70c7-43cf-9ed9-2650a97f76dc.png)
> 
> Also, not sure if it was like that before, but at least now when you select an option, the dropdown collapses and if you want to select more, you need to expand it again. Should it be like that?

Thank you for your fast reviews @alexlioliopoulos! Something happened in the rebase but I hope it's fixed now. :)

2022-09-19 14:05 UTC, alexlioliopoulos commented
> > Something seems to be off now, it was not like that before. Check here:
> > ![image](https://user-images.githubusercontent.com/76053160/191022441-bee5abde-70c7-43cf-9ed9-2650a97f76dc.png)
> > Also, not sure if it was like that before, but at least now when you select an option, the dropdown collapses and if you want to select more, you need to expand it again. Should it be like that?
> 
> Thank you for your fast reviews @alexlioliopoulos! Something happened in the rebase but I hope it's fixed now. :)

They are both fixed now, super nice!

2022-09-20 12:11 UTC, theJohnnyMe approved these changes
Nice work Emelie! It looks good to me :)

2022-09-22 13:15 UTC, merged

2022-11-17 15:44 UTC, mJarsater commented on components/src/components/dropdown/dropdown-option.tsx
> +  }
This will stop all custom onClick