fix(toggles): move theming rules to component folder
scania-digital-design-system/sdds pull request #462
Opened 2022-09-22 11:52 UTC by EmelieLitwin

**Describe pull-request** 
Moving theming rules to component folder 

**Solving issue** 
Fixes: AB#2224

 **How to test** 
1. Open toggles in Storybook of this branch
2. Open toggles in Storybook of production
3.  Compare styling- there should not be any difference between those two

2022-09-22 11:55 UTC, alexlioliopoulos approved these changes

2022-09-26 11:51 UTC, albinscania requested changes
The color is off on the handle between main-branch and the deployed version. Probably just a simple variable error?

2022-09-26 11:54 UTC, theJohnnyMe commented
> The color is off in the disabled state between main-branch and the deployed version. Probably just a simple variable error?

@EmelieLitwin - Please check if you have the latest changes in your local main branch, maybe it is just a commit missing.

2022-09-26 13:06 UTC, theJohnnyMe approved these changes

2022-09-26 13:46 UTC, albinscania approved these changes
Fixed during dev-call with the rest of the team

2022-09-26 13:46 UTC, merged