feat(link): migrate link component
scania-digital-design-system/sdds pull request #495
Opened 2022-10-12 09:47 UTC by alexandereneroth

Migrate link component

Fixes: [AB#2399](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2399)

2022-10-12 10:07 UTC, mJarsater approved these changes
Looks good to me

2022-10-12 12:16 UTC, mJarsater commented on components/src/components/link/link.stories.ts
> +};
Should this be a new story? Or would we want to streamline it and let the users view this via the controls.

2022-10-12 14:06 UTC, alexandereneroth commented on components/src/components/link/link.stories.ts
> +};
I feel like there's value to displaying the different variations to the user up front.
Some examples:
- https://digitaldesign.scania.com/components/datepicker/code 
- https://chakra-ui.com/docs/components/link/usage
- https://mui.com/joy-ui/react-link/

2022-10-12 14:44 UTC, mJarsater commented on components/src/components/link/link.stories.ts
> +};
Absolutely, I think this also is a question of how user actually use the site. Are they interacting with the controls or are they checking the stories.

2022-10-19 07:57 UTC, theJohnnyMe requested changes
Please leave only the "Default" story in this one. It is a very simple component. Thanks for fixing the disabled state too.

2022-10-19 15:12 UTC, alexandereneroth commented
> Please leave only the "Default" story in this one. It is a very simple component. Thanks for fixing the disabled state too.

Removed the other stories. 
Also added a demo class with a font size so the text is not tiny.

2022-10-20 10:31 UTC, mJarsater commented on components/src/components/link/link.stories.ts
> +const defaultArgs = {
Is this object needed? The default values are already present in the default export.

2022-10-20 14:19 UTC, merged