feat(popover-canvas): migrate popover-canvas
scania-digital-design-system/sdds pull request #528
Opened 2022-10-21 11:37 UTC by mJarsater

**Describe pull-request**  
Migration popover-canvas

**Solving issue**  
Fixes: AB#2412

**How to test**  
1. Go to storybook link below
2. Check in components -> popover-canvas
3. Check that the design is aligned with the one in Figma.

**Screenshots**  
-

**Additional context**  
-

2022-10-21 15:12 UTC, alexandereneroth requested changes

2022-10-21 15:12 UTC, alexandereneroth commented on tegel/src/components/popover-canvas/popover-canvas.stories.ts
> +      <div style="display: flex; flex-wrap: nowrap; align-items: center;">
Maybe we should use demo- classes here to be consistent

2022-10-24 11:26 UTC, theJohnnyMe approved these changes
Looks good to me.

2022-10-24 13:57 UTC, theJohnnyMe approved these changes

2022-10-25 11:56 UTC, alexandereneroth approved these changes

2022-10-25 11:57 UTC, alexandereneroth commented
> @alexandereneroth - I think it needs your review too, maybe some of the conversations are unresolved.

approved :)

2022-10-25 11:57 UTC, merged