feat(tabs): migrate tabs components
scania-digital-design-system/sdds pull request #534
Opened 2022-10-24 12:41 UTC by alexandereneroth

Draft PR, WIP

**Describe pull-request**  
_Describe what the pull-request is about_

**Solving issue**  
_In case of GitHub issue add # plus the number of the issue (for example #123) OR if it is Azure then AB# and number of ticket_
Fixes: #

**How to test**  
_Add description how to test if possible_
1. Go to...
2. Check in...
3. Run ...

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

2022-10-28 09:34 UTC, mJarsater commented on tegel/src/components/tabs/inline-tabs/inline-tabs.stories.ts
> +    .sdds-theme-dark .demo-wrapper {
Is this one still needed?

2022-10-28 09:39 UTC, mJarsater commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
> +Basic.args = {};
Rename to Default.

2022-10-28 09:42 UTC, mJarsater commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
Should we maybe add a cursor: not-allowed here?

2022-11-01 11:26 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
@mJarsater Do we have this in other places?
@theJohnnyMe What do you think?

2022-11-01 11:29 UTC, mJarsater commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
For the buttons we use it 😄

2022-11-01 11:37 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
I suggest we make a separate issue for this to make it consistent everywhere.
I suspect there are other inconsistencies as well

2022-11-01 11:52 UTC, mJarsater commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
Agree 👍🏻

2022-11-01 11:58 UTC, mJarsater commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
Created a ticket here: https://dev.azure.com/scaniadigitaldesignsystem/SDDS/_backlogs/backlog/Product%20Team/Features/?workitem=2476

2022-11-02 09:19 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +    pointer-events: none;
As you talked here and yesterday during the grooming, let do it in separate ticket ;)

2022-11-02 09:43 UTC, theJohnnyMe requested changes

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +  ::slotted(&--tab__disabled) {
Not sure if is it the right place, but please check if we can disable the focus state for disabled items.
Only this variation of tabs gets focus state on disabled item: 

<img width="748" alt="Screenshot 2022-11-02 at 10 21 51" src="https://user-images.githubusercontent.com/17004063/199453762-dec72c1b-c83f-4df9-99b8-e9c61a1e4632.png">

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +@mixin sdds-focus-state {
Try to import this one from the mixins folder instead.

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs/inline-tabs.scss
> +@mixin sdds-focus-state {
Try to import this one from the mixins folder.

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs/inline-tabs.tsx
> +  // public method for switching to a tab programmatically
Please add comments here in a format as it is done for Prop above, with /** */ so it displays in README

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
> +  parameters: {
Maybe add a layout parameter for a fullscreen view, what do you think?

2022-11-02 09:43 UTC, theJohnnyMe commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
> +    notes: readme,
Maybe also a fullscreen layout here, what do you think?

2022-11-02 14:33 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +  ::slotted(&--tab__disabled) {
I think we should rather make the other disabled controls focusable. If they are not, someone using a screenreader might not discover that they exist.
Saw this https://ux.stackexchange.com/a/103246

What do you think?

2022-11-03 08:43 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +@mixin sdds-focus-state {
fixed

2022-11-03 08:44 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs/inline-tabs.scss
> +@mixin sdds-focus-state {
fixed

2022-11-03 08:53 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.stories.ts
> +  parameters: {
Personally i like that there is a bit of padding around it in the example, i think you can see the edges of it better, also it looks more consistent with other stories 🤔

2022-11-03 08:54 UTC, alexandereneroth commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs.stories.ts
> +    notes: readme,
Personally i like that there is a bit of padding around it in the example, i think you can see the edges of it better, also it looks more consistent with other stories 🤔

2022-11-03 08:57 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs/inline-tabs.tsx
> +  // public method for switching to a tab programmatically
fixed

2022-11-07 12:36 UTC, theJohnnyMe commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed.scss
> +  ::slotted(&--tab__disabled) {
I did not know about this, but good that you came back with a comment. Then let's keep it.

2022-11-07 12:41 UTC, theJohnnyMe approved these changes
Nice work man, LGTM! ;)

2022-11-07 12:58 UTC, merged