Migrate dropdown2
scania-digital-design-system/sdds pull request #544
Opened 2022-10-26 08:05 UTC by EmelieLitwin

**Describe pull-request**  
Migrating dropdown

**Solving issue**  
Azure ticket AB#2385

2022-10-26 08:07 UTC, EmelieLitwin commented
Readme is still for dropdown-option

2022-10-27 07:27 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown.stories.js
> +import readme from './readme.md';
Maybe Stecil expects only one component per folder and therefor only creates on readme? In that case I guess we would have to create an internal folder structure to "hide" away the components subcomponents.

2022-10-27 07:28 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown.stories.js
> +        options: { Large: 'lg', Medium: 'md', Small: 'sm' },
This is nice! Means that we can get rid of a lot of switches in other components that assignes "Small" to "sm" for instance. 👍🏻

2022-10-27 11:14 UTC, mJarsater requested changes

2022-10-27 11:14 UTC, mJarsater commented on tegel/src/components/checkbox/checkbox.stories.ts
>  import { formatHtmlPreview } from '../../utils/utils';
Should these changes be part of this PR?

2022-10-27 11:14 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-filter.stories.js
> +import { formatHtmlPreview } from '../../utils/utils';
Should this be a separate component in storybook? I would say that we include it under dropdown.

2022-10-28 13:37 UTC, EmelieLitwin commented on tegel/src/components/checkbox/checkbox.stories.ts
>  import { formatHtmlPreview } from '../../utils/utils';
Thank you, I missed this. Not sure what what happened there!

2022-10-28 13:44 UTC, EmelieLitwin commented on tegel/src/components/dropdown/dropdown-filter.stories.js
> +import { formatHtmlPreview } from '../../utils/utils';
We talked a little about it at some point. The main reason is that it's its own component `<sdds-dropdown-filter>` unlike multiselect for example that is `<sdds-dropdown type='multiselect'>` plus it's got a separate readme.

2022-10-28 13:49 UTC, EmelieLitwin commented on tegel/src/components/dropdown/dropdown.stories.js
> +import readme from './readme.md';
I spent a some time finding different ways to trick stencil to generate a readme, but I was unsuccessful and felt like I had to move on but I definitely want to revisit it! At my last workplace all subcomponents had their own folders and were documented separately. Much easier 😆

2022-10-31 10:49 UTC, theJohnnyMe commented
I am getting this on my local, please double-check: 

![Screenshot 2022-10-31 at 11 48 11](https://user-images.githubusercontent.com/17004063/198991181-be0b12ef-d11b-4704-a60e-930e2748152f.png)


![Screenshot 2022-10-31 at 11 48 38](https://user-images.githubusercontent.com/17004063/198991231-34d587af-edfb-4142-b0bb-9d7ba028b9af.png)

2022-11-02 12:33 UTC, theJohnnyMe approved these changes
There is an issue with the multi-select one, but let's keep it out of the scope of this task.

2022-11-03 11:02 UTC, alexandereneroth requested changes

2022-11-07 12:24 UTC, alexandereneroth commented on tegel/src/components/dropdown/dropdown.tsx
> +      console.warn('size="small" is deprecated, use size="sm" instead');
nice!

2022-11-07 12:30 UTC, alexandereneroth requested changes

2022-11-07 12:30 UTC, alexandereneroth commented on tegel/src/components/dropdown/dropdown.tsx
> +      this.open ? !this.open : this.open;
This expression doesn't do anything, probably a bug here if we expect this to do something

2022-11-08 15:11 UTC, alexandereneroth approved these changes
Nice work! ✨

2022-11-08 15:14 UTC, merged