fix(data-table): migration to tegel
scania-digital-design-system/sdds pull request #571
Opened 2022-11-04 16:15 UTC by theJohnnyMe

**Describe pull-request**  
Migration of data-table component

**Solving issue**  
Fixes: AB#2455

**How to test**  
_Add description how to test if possible_
1. Go to...
2. Check in...
3. Run ...

**Additional context**  
IN PROGRESS

2022-11-10 09:33 UTC, mJarsater commented
I am getting some curly crackets in the code example that I don't think are suppose to be there.

![Screenshot 2022-11-10 at 10 32 18](https://user-images.githubusercontent.com/62651103/201053941-eaba01ed-de36-4e43-937c-7e65cf30f415.png)

2022-11-10 09:51 UTC, mJarsater commented on tegel/src/components/data-table/table-component-basic.stories.ts
> +          <sdds-header-cell column-key='mileage' column-title='Mileage' text-align='right' }></sdds-header-cell>
Remove curly brackets.

2022-11-10 09:57 UTC, mJarsater commented on tegel/src/components/data-table/table-component-basic.stories.ts
> +      'sdds-table-footer': sddsTableFooter,
Really nice way of handling multiple readme's!

2022-11-10 10:02 UTC, mJarsater commented on tegel/src/components/data-table/table-component-event-listeners.stories.ts
> +  <h3>Disabled filtering, pagination and sorting - left to the user to listen to events</h3>
Maybe add a subheadline here informing the user this only work  in the canvas tab?

2022-11-10 10:03 UTC, mJarsater commented on tegel/src/components/data-table/table-component-multiselect.stories.ts
> +   <sdds-table
Maybe add a subheadline here informing the user this only work in the canvas tab?

2022-11-10 10:04 UTC, mJarsater commented on tegel/src/components/data-table/table-component-event-listeners.stories.ts
> +    <h5>Event test box</h5>
Maybe add a subheadline here informing the user this only work in the canvas tab?

2022-11-10 10:10 UTC, mJarsater requested changes
Remove unnecessary curly brackets on the <sdds-header-cell> on multiple stories. Otherwise it looks good to me, really nice work!

2022-11-10 16:17 UTC, theJohnnyMe commented on tegel/src/components/data-table/table-component-basic.stories.ts
> +      'sdds-table-footer': sddsTableFooter,
Yeah, Emelie did it for Dropdown first as it is also more than one component and I felt it makes sense to have all of them in all stories so users have access to it.

2022-11-10 16:18 UTC, theJohnnyMe commented on tegel/src/components/data-table/table-component-multiselect.stories.ts
> +    <h6 class="sdds-u-pb0 sdds-u-mb0">Selected rows data</h6>
Absolutely, good call!

2022-11-10 16:18 UTC, theJohnnyMe commented on tegel/src/components/data-table/table-component-event-listeners.stories.ts
> +    <h5>Event test box</h5>
Absolutely, good call!

2022-11-10 16:50 UTC, theJohnnyMe commented
@mJarsater  - Thanks for review buddy, I think all comments are sorted out now, please double check ;)

2022-11-11 07:27 UTC, mJarsater approved these changes
Nice!

2022-11-11 08:05 UTC, merged