fix(dropdown): inside label full size when no option is selected
scania-digital-design-system/sdds pull request #584
Opened 2022-11-09 12:48 UTC by EmelieLitwin

**Same as previous PR but made to old main.**

**Describe pull-request**
Dropdown with label inside is not rendering the label properly when no option is selected. Not changed for new Tegel components yet

**Solving issue**
Github issue https://github.com/scania-digital-design-system/sdds/issues/440 and Azure ticket [AB#2321](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2321)

**How to test**

- Go to storybook
- Check dropdown label inside and see if it looks correct

2022-11-10 10:02 UTC, alexandereneroth requested changes
When i use label position inside and manually select an option it looks like this for me:
<img width="320" alt="Screenshot 2022-11-10 at 11 01 12" src="https://user-images.githubusercontent.com/8556022/201061066-3ea8b51e-2d99-47bc-bd3e-b622ed154e7a.png">

(tested in our storybook)

2022-11-11 08:10 UTC, theJohnnyMe commented
> When i use label position inside and manually select an option it looks like this for me: <img alt="Screenshot 2022-11-10 at 11 01 12" width="320" src="https://user-images.githubusercontent.com/8556022/201061066-3ea8b51e-2d99-47bc-bd3e-b622ed154e7a.png">
> 
> (tested in our storybook)

Great catch!

2022-11-11 08:11 UTC, theJohnnyMe requested changes
+1 on Alex finding

2022-11-11 15:57 UTC, theJohnnyMe approved these changes

2022-11-11 16:06 UTC, merged