fix/standardise storybook control option and default options
scania-digital-design-system/sdds pull request #586
Opened 2022-11-09 15:23 UTC by mJarsater

**Describe pull-request**  
This PR standardises the controls and default options for all components.

**Solving issue**  
Fixes: [AB#2483](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2483)

**How to test**  
1. Go to storybook link below
2. Check in all components and try out the controls.

### NOTE
This PR also replaces svgs with out own icons, and gives the user the option of having either a webcomponent or native one.

2022-11-10 10:57 UTC, alexandereneroth requested changes
Awesome work! Just spotted a few remaining `defaultValue`, if you fix those i'll approve it

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/stepper/stepper.stories.js
>        defaultValue: 'Default',
🕵️

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/stepper/stepper.stories.js
>        defaultValue: 'Default',
🕵️

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/stepper/stepper.stories.js
> +      defaultValue: true,
🕵️

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/textarea/textarea.stories.js
>        defaultValue: 'No label',
defaultValue 👆

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/toast/toast.stories.ts
> +        color: var(--sdds-${colorLooup[toastType]})
Missing semicolon ;

2022-11-10 10:57 UTC, alexandereneroth commented on tegel/src/components/toast/toast.stories.ts
> +        color: var(--sdds-${colorLooup[toastType]})
Missing semicolon ;

2022-11-10 11:07 UTC, mJarsater commented
> Awesome work! Just spotted a few remaining `defaultValue`, if you fix those i'll approve it

Thanks! Yeah im working on those in a separate branch that I'm gonna merge into this one

2022-11-10 14:05 UTC, mJarsater commented on tegel/src/components/button/button-webcomponent.stories.ts
> +  const btnTypeLookUp = {
Yeah I guess this goes for all lookup objects. I can do them all in one commit.

2022-11-11 10:35 UTC, alexandereneroth requested changes
Some final few things 👍

2022-11-11 12:05 UTC, mJarsater commented on tegel/src/components/stepper/stepper.stories.js
> +  let sizeClass = size === 'Small' ? 'sdds-stepper--small' : '';
Nice!

2022-11-11 12:07 UTC, mJarsater commented on tegel/src/components/block/block.stories.ts
> -        <div class="sdds-block">
Not sure I get what you mean here?

2022-11-11 12:15 UTC, mJarsater commented on tegel/src/components/block/block.stories.ts
> -        <div class="sdds-block">
Never mind! Pushed a change.

2022-11-11 13:17 UTC, alexandereneroth approved these changes
Great work once again!

2022-11-11 13:25 UTC, theJohnnyMe requested changes

2022-11-11 13:25 UTC, theJohnnyMe commented on tegel/src/components/toast/toast.scss
> +    margin: 13.5px 0 0 3rem;
Please try to replace this one with:
```suggestion
    margin: 14px 0 0 12px;
```

I am not sure if 0.5px works on screens + let's have px values everywhere for consistency.

2022-11-11 13:25 UTC, theJohnnyMe commented on tegel/src/components/toast/toast.stories.ts
> +    },
Please set one of them as default as the story ends up with non of them pre-selected. I would say when in doubt, make the component version default.

2022-11-11 13:34 UTC, theJohnnyMe commented
I found really tiny things, I tried to go commit by commit. 
I found some more stuff but they are not related to your changes. all in all, awesome work on standardizing buddy! 🚀

2022-11-11 14:09 UTC, mJarsater commented
> I found really tiny things, I tried to go commit by commit. I found some more stuff but they are not related to your changes. all in all, awesome work on standardizing buddy! 🚀

Thanks! Great, I re-requested your feedback now, after I fixed your suggested changes 😄

2022-11-11 14:19 UTC, theJohnnyMe approved these changes
Gods work!

2022-11-11 14:23 UTC, merged