feat(): storybook add-on design a11y and screan reader
scania-digital-design-system/sdds pull request #632
Opened 2022-11-22 14:40 UTC by EmelieLitwin

Added storybook add-on for Figma, a11y and screen reader.
Added figma files for accordion to datetime so far, but it's a bit time consuming to add individually so want to see if you like it first.

2022-11-23 14:30 UTC, mJarsater commented
I like it. I don't know if this is something we should pick up later down the line though (the figma part)? If it's very tedious and time consuming.

2022-11-25 10:40 UTC, theJohnnyMe commented
I agree with Martin. Please check how you feel about adding Figma links to all components. 
My suggestion is either we add it to all of them now or we remove it for now and we come back to it later.
I am 1% more for adding it to all components now as "later" tends to get delayed a lot.

2022-11-25 11:03 UTC, alexandereneroth requested changes

2022-11-25 11:03 UTC, alexandereneroth commented on tegel/src/components/accordion/accordion.stories.ts
> +  ],
And same with the rest of the components i suspect

2022-11-30 12:15 UTC, closed without merging