fix(dropdown): label placement and padding
scania-digital-design-system/sdds pull request #669
Opened 2022-11-30 10:11 UTC by mJarsater

**Describe pull-request**  
Changed the bottom padding for the button if the label is inside, also refactored the positioning of the actual inside label. Fixes for both components and tegel.

**Solving issue**  
Fixes: AB#2463 #550

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Dropdown
3. Check the placement of the inside label and bottom padding of the button when there is an inside label.

**Screenshots**  
-

**Additional context**  
-

2022-11-30 12:37 UTC, EmelieLitwin commented
The inside label specs are hard to review but it looks good! 👍 
I think the label and the chevron are grey-958 instead of grey-700, maybe that could be fixed in this pr?

2022-12-05 10:59 UTC, theJohnnyMe requested changes
When there is no label inside and the component size is "Medium", the text is not in the vertical center. I tested by changing the values of padding to 16px and it looks like one in the Figma file. Please check if that would work for you.

2022-12-05 10:59 UTC, theJohnnyMe commented on tegel/src/components/dropdown/dropdown.scss
> +        padding-bottom: 12px;
```suggestion
        padding-bottom: 16px;
```

2022-12-05 10:59 UTC, theJohnnyMe commented on components/src/components/dropdown/dropdown.scss
> +        padding-bottom: 12px;
```suggestion
        padding-bottom: 16px;
```

2022-12-05 12:10 UTC, mJarsater commented
> When there is no label inside and the component size is "Medium", the text is not in the vertical center. I tested by changing the values of padding to 16px and it looks like one in the Figma file. Please check if that would work for you.

Nice catch! I updated the PR and moved all the padding styling from our dropdown-core.scss to dropdown.scss in order to handle sizes better. Please give it a look 😄

2022-12-07 16:07 UTC, mJarsater commented
> @mJarsater - Please double-check the native story, it seems that one needs an update with sizing classes now.

Should be fixed now. Still pondering if we should release this as a fix or just skip it and fix it once we refactor the component?

2022-12-08 15:16 UTC, theJohnnyMe approved these changes
LGTM

2022-12-08 15:17 UTC, theJohnnyMe commented
> > @mJarsater - Please double-check the native story, it seems that one needs an update with sizing classes now.
> 
> Should be fixed now. Still pondering if we should release this as a fix or just skip it and fix it once we refactor the component?

If there is anything left, please add it as a ticket so we do not forget about it.

2022-12-08 15:48 UTC, merged