docs(textfield): refactored the controls regarding  prefix/suffix
scania-digital-design-system/sdds pull request #674
Opened 2022-12-01 09:05 UTC by mJarsater

**Describe pull-request**  
Refactored the controls regarding  prefix/suffix.

**Solving issue**  
Fixes: AB#2676

**How to test**  
1. Go to storybook
2. Check in Components -> Textfield
3. Test the controls for the suffix/prefix.

**Screenshots**  
-

**Additional context**  
-

2022-12-01 09:16 UTC, mJarsater commented
Question for everyone, should we hide the suffix if readonly is true?

2022-12-05 12:33 UTC, theJohnnyMe requested changes

2022-12-05 12:33 UTC, theJohnnyMe commented on tegel/src/components/textfield/textfield.stories.ts
> +// ${true ? '<sdds-icon name="cross" slot="sdds-prefix"></sdds-icon>' : ''}
I guess this can be removed.

2022-12-05 12:36 UTC, mJarsater commented on tegel/src/components/textfield/textfield.stories.ts
> +// ${true ? '<sdds-icon name="cross" slot="sdds-prefix"></sdds-icon>' : ''}
Woops! Absolutely 😄

2022-12-05 12:36 UTC, mJarsater commented on tegel/src/components/textfield/textfield.stories.ts
> +// ${true ? '<sdds-icon name="cross" slot="sdds-prefix"></sdds-icon>' : ''}
```suggestion
```

2022-12-05 15:12 UTC, closed without merging