fix(textarea/textfield): label position label props
scania-digital-design-system/sdds pull request #676
Opened 2022-12-01 11:40 UTC by mJarsater

**Describe pull-request**  
Changed the label/labelPosition props to align the component with each other. After this change both components have label="Label text" and label-position="inside | outside | no-label". 

**Solving issue**  
Fixes: [AB#2742](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2742)

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Textarea/Textfield
3. Check that the controls and the example code works as they should.

**Screenshots**  
-

**Additional context**  
-

2022-12-05 12:38 UTC, theJohnnyMe requested changes

2022-12-05 12:38 UTC, theJohnnyMe commented on tegel/src/components/textarea/textarea.stories.ts
>      label: '',
Please add some text here for the story example.

2022-12-05 12:38 UTC, theJohnnyMe commented on tegel/src/components/textfield/textfield.stories.ts
>      label: '',
Please add some text here for the story example.

2022-12-05 12:39 UTC, theJohnnyMe commented
Really nice work man, thanks for aligning these. 🚀

2022-12-05 12:44 UTC, mJarsater commented on tegel/src/components/textarea/textarea.stories.ts
>      label: '',
```suggestion
    label: 'Label',
```

2022-12-05 12:44 UTC, mJarsater commented on tegel/src/components/textfield/textfield.stories.ts
>      label: '',
```suggestion
    label: 'Label',
```

2022-12-06 09:19 UTC, theJohnnyMe approved these changes
Nice work man 🚀

2022-12-06 09:38 UTC, EmelieLitwin approved these changes
Great job! 🥳

2022-12-06 10:04 UTC, merged