feat(inline-tabs/inline-tabs-fullbleed): added variant prop
scania-digital-design-system/sdds pull request #687
Opened 2022-12-02 11:51 UTC by mJarsater

**Describe pull-request**  
Added a variant prop to allow user to use the on white/on grey options. 

**Solving issue**  
Fixes: AB#2751

**How to test**  
1. Check out the branch and run start for components.
2. Check in that the variant controls works as intended. 
3. Check the storybook link below.
4. Check in that the variant controls works as intended for tegel. 

**Screenshots**  
-

**Additional context**  
-

2022-12-06 10:03 UTC, EmelieLitwin reviewed
Variant primary/secondary is still called themeVariant on-white etc in figma, should this be changed there as well?

2022-12-06 10:14 UTC, mJarsater commented
> /secondary is still called themeVariant on-white etc in figma, should this be changed there as well?

If that's ok with the designers I would say yes

2022-12-08 15:31 UTC, theJohnnyMe requested changes
As we discussed yesterday with the designers:

1. name the prop `mode-variant`
2. rename the Storybook control to "Mode variant"
3. Primary is on-white, secondary is on-grey
4. If not defined by the user, the component take primary as the "default" value.

2022-12-08 21:48 UTC, theJohnnyMe approved these changes
Awesome man!

2022-12-09 07:27 UTC, merged