feat(dropdown-option): adding disabled state
scania-digital-design-system/sdds pull request #689
Opened 2022-12-02 16:52 UTC by theJohnnyMe

**Describe pull-request**  
Adding disabled state to dropdown option

**Solving issue**  
Fixes: AB#2549 #589 

**How to test**  
1. Go to the dropdown component
2. In both the default web component and multi-select one, there is one item that is disabled
3. Try to select it, it should not be possible

**Additional context**  
Currently, this fix is not involving filtering type of dropdown. 
The feature is done for both the component and Tegel package
The design of a disabled state has to be verified by one of our designers.

2022-12-06 07:07 UTC, mJarsater requested changes
LGTM other than double dash on 'sdds-dropdown-option--disabled'. I would suggest we change it to single dash 'sdds-dropdown-option-disabled' to conform with convention.

2022-12-06 08:13 UTC, matyldamc commented
The functionality works, but I think there might be some visual issues between the multi-select web component, and what's in the Figma UI library. Screenshot attached showing what's in Storybook, and Figma.
<img width="1458" alt="Screenshot 2022-12-06 at 09 11 30" src="https://user-images.githubusercontent.com/91310967/205856483-5e19bfa7-0932-4024-956a-7716de5f46a9.png">

2022-12-06 10:27 UTC, theJohnnyMe commented
> LGTM other than double dash on 'sdds-dropdown-option--disabled'. I would suggest we change it to single dash 'sdds-dropdown-option-disabled' to conform with convention.

Great catch! It should be fixed now!

2022-12-06 10:30 UTC, theJohnnyMe commented
> The functionality works, but I think there might be some visual issues between the multi-select web component, and what's in the Figma UI library. Screenshot attached showing what's in Storybook, and Figma. <img alt="Screenshot 2022-12-06 at 09 11 30" width="1458" src="https://user-images.githubusercontent.com/91310967/205856483-5e19bfa7-0932-4024-956a-7716de5f46a9.png">

I think you accidentally went into "dark mode" where we have not yet updated variables to correct one - dark mode is still under development. Please check in "light mode", make sure this icon is appearing:    
![Screenshot 2022-12-06 at 11 28 50](https://user-images.githubusercontent.com/17004063/205887089-31b39d6e-68ff-4763-80ae-f573c367d583.png)

PS: Charlotte and I had sync on colors to so I have updated the disabled test to grey-400, while the background color stays the same.

2022-12-06 10:38 UTC, matyldamc commented
@theJohnnyMe ok good to know! In that case, the only thing that's off is the background color of the selected-disabled option should be white :)
<img width="1281" alt="Screenshot 2022-12-06 at 11 37 13" src="https://user-images.githubusercontent.com/91310967/205888999-bc6a88f8-a304-4047-a508-dfca3530b429.png">

2022-12-06 10:42 UTC, matyldamc approved these changes
@theJohnnyMe disregard my comment about the bg state. Didn't read your entire post :) Approved!

2022-12-08 15:46 UTC, mJarsater approved these changes
LGTM

2022-12-08 22:11 UTC, merged