fix(tegel): remove base value and use px instead of rem
scania-digital-design-system/sdds pull request #691
Opened 2022-12-05 09:59 UTC by mJarsater

**Describe pull-request**  
Refactored tegel to not import reboot.scss. This removes the font-size: 4px on on the html tags. Removed the use of rem is all components/stories. Refactored all use of rem to px in theme/core. Refactored all use of rem to px in spacing and typography. 

**Solving issue**  
Fixes: [AB#2522](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2522)

**How to test**  
1. Checkout branch and run npm build on root level.
2. Cd into tegel and run npm run tegel
3. Check in Foundations -> Grid/Spacing/Typography and make sure the stories look good.
4. A couple of random components and make sure the are using the correct px instead of any rem values.

**Screenshots**  
-

**Additional context**  
-

2022-12-05 14:01 UTC, alexandereneroth requested changes
Nice work, left a few comments. 
Also i think we should leave some lines about these changes in the migration document.

2022-12-05 14:08 UTC, mJarsater commented on tegel/src/components/theme/grid/grid.stories.ts
> +  <h4 class="sdds-headline-04">Grid</h4>
Do you mean the removal of rem overall? Or something specific on these lines? 😄

2022-12-05 14:22 UTC, mJarsater commented on theme/core/spacing/spacing-vars.scss
>  // Layout scale
The first one is just the tokens right? And this one gets auto-generated to create css variables. Not sure why we do it that way though.

2022-12-05 14:25 UTC, mJarsater commented on tegel/src/components/theme/grid/grid.stories.ts
> +  <h4 class="sdds-headline-04">Grid</h4>
Ah alright, I'va added a "chapter" in migration docs, but I do thing it could be added to.

2022-12-05 14:25 UTC, mJarsater commented on tegel/src/components/theme/grid/grid.stories.ts
> +  <h4 class="sdds-headline-04">Grid</h4>
```suggestion
  <h4>Grid</h4>
```

2022-12-05 14:28 UTC, alexandereneroth requested changes

2022-12-05 14:28 UTC, alexandereneroth commented on tegel/src/stories/Migration/Migration.stories.mdx
> +Ideally this change should not affect you, but since it is something that has an affect on all components
Maybe instead: "If you are not using rem yourself, this change should not affect you".

And we could also write something about what to do if they are using rems

2022-12-05 14:29 UTC, mJarsater commented on tegel/src/stories/Migration/Migration.stories.mdx
> +Ideally this change should not affect you, but since it is something that has an affect on all components
Yeah, nice!

2022-12-05 14:43 UTC, mJarsater commented on tegel/src/stories/Migration/Migration.stories.mdx
> +## What action is required?
```suggestion
#### What action is required? 
```

2022-12-05 16:39 UTC, alexandereneroth approved these changes
LGTM

2022-12-05 16:39 UTC, alexandereneroth commented on tegel/src/stories/Migration/Migration.stories.mdx
> +recalculated.
```suggestion
## Removed base font-size and moved to `px` instead of `rem`.

This change affects all components/typography/spacing/grid. 

In the past we have used a base value of 4px
that has been used to calculate the spacing/padding/margins etc with rem. This was done by setting the 
base value (4px) as the font-size on the `<html>`-element, which for some users has caused error with 
custom font-sizes. We have now removed these dependencies and are using pixels in our 
components/spacing/typography/margins.

We are doing this to decrease the dependencies between our packages and we want to make sure the Tegel
can be used on its own. 

#### What action is required? 

If you are not yourself using `rem` your project ideally this change should not affect you, but since it is 
something that has an effect on all components and utilities/foundations we expect that there might be some
unforeseen problems. These will have our highest prio in order to make the migration to Tegel as smooth as possible.

If you are however using `rem` in your project you would have to consider that the base value will no longer be `4px`.
This value will now by default be `16px`. So for the element in you project that are using rem these would have to be 
recalculated.
```

2022-12-05 16:43 UTC, alexandereneroth commented
Although i now see the vertical spacing in the migration document got substantially bigger

2022-12-06 07:02 UTC, mJarsater commented on tegel/src/stories/Migration/Migration.stories.mdx
> +If you are not yourself using `rem` your project ideally this change should not affect you, but since it is
```suggestion
If you are not yourself using `rem` in your project ideally this change should not affect you, but since it is 
```

2022-12-06 07:08 UTC, mJarsater commented
> LGTM

Nice, since it's a pretty big change I'll hold off on merging it until we have had some more reviews ✌🏻

2022-12-06 13:24 UTC, theJohnnyMe requested changes
Please remove `"@scania/typography": "^1.2.1"` from Tegel's package.json file, drop node_modules and run the installation again.
Let's see how Tegel behaves without it. I would like the Tegel package consumes "raw" typography SCSS and let Stencil compiles it so we can see immediate changes - same as we did for spacing, colors etc... I think it might be cleaner and won't give us false positives or false negatives. 

PS: Typography stories will brake, but it gives a good hint about which "raw" typography files we have to include in `globals.scss ` .

2022-12-06 13:50 UTC, mJarsater commented
> Please remove `"@scania/typography": "^1.2.1"` from Tegel's package.json file, drop node_modules and run the installation again. Let's see how Tegel behaves without it. I would like the Tegel package consumes "raw" typography SCSS and let Stencil compiles it so we can see immediate changes - same as we did for spacing, colors etc... I think it might be cleaner and won't give us false positives or false negatives.
> 
> PS: Typography stories will brake, but it gives a good hint about which "raw" typography files we have to include in `globals.scss ` .

Good idea! I have removed it now and it seems like the only thing affected is the typography story 😄

2022-12-07 15:57 UTC, theJohnnyMe approved these changes
LGTM!

2022-12-07 16:01 UTC, merged