feat(modal): refactored how we open the modal and removed prop selector
scania-digital-design-system/sdds pull request #700
Opened 2022-12-06 12:25 UTC by mJarsater

**Describe pull-request**  
Refactored how we open the modal and removed prop selector, updated the story and added to migration docs

BREAKING CHANGE: Removed the selector prop and added prop for open.

**Solving issue**  
Fixes: [AB#2739](https://dev.azure.com/scaniadigitaldesignsystem/3d9eb9c6-0045-473d-bc1d-e842dd779200/_workitems/edit/2739)

**How to test**  
_Add description how to test if possible_
1. Go to storybook link below.
2. Check in Components -> Modal -> Web component
3. Check that the modal works as expected.
4. Check the added chapter in migration docs.

**Screenshots** 
-

**Additional context** 
-

2022-12-08 08:43 UTC, alexandereneroth commented on tegel/src/components/modal/modal.tsx
> +        }}
```suggestion
        onClick={this.handleClick}
```
Did you try this?

2022-12-08 08:45 UTC, mJarsater commented on tegel/src/components/modal/modal.tsx
> +        }}
Yeah and that works fine, I'll commit it!

2022-12-08 09:41 UTC, alexandereneroth requested changes
I like 👍 But suggested some changes to the migration file text 👇

2022-12-08 09:41 UTC, alexandereneroth commented on tegel/src/stories/Migration/Migration.stories.mdx
> +and this approach gives you more freedom on how you open your modals.
```suggestion
The modal component was previously opened via a selector that was added on a button,
which would be the controller of the modal. This has now been changed and the modal is
now opened based on its own boolean prop, called `open`. This change is done in order to
make the component more in line with how these sort of thing are generally done. We also
don't want to assume that the open/closed state of the modal is controlled by a button. This approach gives you more freedom on how you open your modals.
```
Reformulated some things, and fixed some typos

2022-12-08 15:48 UTC, theJohnnyMe requested changes

2022-12-08 15:48 UTC, theJohnnyMe commented on tegel/src/components/modal/modal.tsx
> -    this.dismissModal();
I think we need dismissModal here in order for buttons with the `data-dismiss-modal` attribute to close. 
What do you think?

2022-12-08 15:51 UTC, mJarsater commented on tegel/src/components/modal/modal.tsx
> -    this.dismissModal();
Do you mean the button within the modal itself or button from outside the modal?

2022-12-08 21:52 UTC, theJohnnyMe commented on tegel/src/components/modal/modal.tsx
> -    this.dismissModal();
I was led by the story example, where both the delete and cancel buttons inside of the dropdown (slotted ones) have that attribute. I wonder if we run that function in the lifecycle or if we completely remove it and rely only on method/prop for closing?

What do you think?

2022-12-09 07:30 UTC, mJarsater commented on tegel/src/components/modal/modal.tsx
> -    this.dismissModal();
Ah alright! I guess the question then if whether or not we want the component to work in that way? Since we are opening/closing the modal by toggling the open prop perhaps these buttons should do that as well. But I don't know if they should by default..

2022-12-09 08:45 UTC, theJohnnyMe approved these changes
Nice work man!

2022-12-09 13:30 UTC, alexandereneroth approved these changes
⭐

2022-12-09 13:34 UTC, merged