Feature/button test
scania-digital-design-system/sdds pull request #72
Opened 2021-02-05 07:52 UTC by iths-jonathan-engman

**Describe pull-request**  
Made some testing components under components/test-comp for storybook

2021-02-08 20:55 UTC, mmexvr commented on components/src/components/button/button-component.tsx
> +  tag: 'test-btn',
I would recommend to maybe rename it

c-button

c = for component 
button = what the component is

2021-02-12 07:44 UTC, helloimela commented on components/src/components/button/button-component.tsx
> +export class CButton {
Change class to Button, since we use different prefix now

2021-02-12 07:45 UTC, helloimela commented on components/src/components/button/button-component.tsx
> +          <span class='sdds-btn-icon'>
Investigate solution if button does not have icon, span sdds-btn-icon should not taking space to the right

2021-02-12 07:48 UTC, helloimela requested changes

2021-02-12 07:48 UTC, helloimela commented on components/src/components/button/button.stories.js
> +  <sdds-button type="primary" size="md" disabled="" fullbleed="true" text="Button"><c-icon name='scania-cross'></c-icon></sdds-button>
Provide storybook args, so that when we change value in control, the button will change according to the given value. Something like size=${size}. See example on ButtonTemplate

2021-02-18 14:27 UTC, mmexvr commented on components/src/components/button/button.scss
> +  width: 16px;
Maybe you can use spacing variables here also?  --sdds-spacing-element-16 for example

2021-02-22 07:47 UTC, helloimela approved these changes
great job!

2021-02-22 07:48 UTC, merged