Change controller name task 2850
scania-digital-design-system/sdds pull request #732
Opened 2022-12-16 10:57 UTC by nathalielindqvist

**Describe pull-request**  
Changed controller name "Variant" to "Mode variant" and options "On light" and "On dark" to "Primary" and "Secondary" on both native and web component Button.

**Solving issue**  
Fixes: AB#2850

**How to test**
1. Go to Storybook
2. Check in component Button, both Native and Web Component

2023-01-02 15:59 UTC, theJohnnyMe approved these changes
LGTM
Please mind the commit message when you "squash and merge" ;)

2023-01-12 07:22 UTC, mJarsater requested changes

2023-01-12 07:22 UTC, mJarsater commented on tegel/src/components/button/button-native.stories.ts
>      variant: {
Change this to modeVariant to reflect the prop. Same goes for other variant args also.

2023-01-25 15:48 UTC, EmelieLitwin commented
This PR is stale right?

2023-01-26 12:26 UTC, nathalielindqvist commented on tegel/src/components/button/button-native.stories.ts
>      variant: {
Done in other PR, rebased onto this.

2023-01-26 12:26 UTC, nathalielindqvist commented on tegel/src/components/button/button-webcomponent.stories.ts
> +      name: 'Mode variant',
Done in other PR, rebased onto this.

2023-01-26 12:26 UTC, nathalielindqvist commented on tegel/src/components/button/button-native.stories.ts
> +    variant: 'Primary',
Done in other PR, rebased onto this.

2023-01-26 15:05 UTC, closed without merging