fix(modal): add dark mode variables
scania-digital-design-system/sdds pull request #747
Opened 2022-12-22 15:40 UTC by EmelieLitwin

**Describe pull-request**  
Dark mode variables

**Solving issue**  
Fixes: AB#2932

2023-01-04 08:46 UTC, theJohnnyMe approved these changes
LGTM ;)

2023-01-04 11:25 UTC, mJarsater requested changes
The "close-button" should be white in dark mode. Is weird how that one today is setting a background image in the css. Should probably be refactored to include a sdds-icon in the html.

2023-01-09 12:24 UTC, EmelieLitwin commented
> The "close-button" should be white in dark mode. Is weird how that one today is setting a background image in the css. Should probably be refactored to include a sdds-icon in the html.

I'm not including it in this pr, but I'll write a ticket for refactoring

2023-01-10 11:38 UTC, mJarsater approved these changes

2023-01-10 13:49 UTC, merged