fix(tabs): add dark mode variables
scania-digital-design-system/sdds pull request #752
Opened 2022-12-27 08:38 UTC by EmelieLitwin

**Describe pull-request**  
Dark mode variables

**Solving issue**  
Fixes: AB#2936

2023-01-03 09:47 UTC, alexandereneroth requested changes
I think the foreground of the scroll buttons should be some shade of white, hard to spot otherwise (inline-tabs, and inline-tabs-fullbleed)
![Screenshot 2023-01-03 at 10 45 33](https://user-images.githubusercontent.com/8556022/210333220-8db5b355-4f26-422d-8c8c-11573e32d9a9.png)

2023-01-04 11:31 UTC, mJarsater approved these changes
LGTM. The color of the disabled state for the inline tabs is very similar to the non disabled one, might be an a11y issue. But that's a design thing. Nice work! 🦄

2023-01-17 10:31 UTC, alexandereneroth requested changes

2023-01-17 10:31 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
> +:root,-hover--sdds-inline-tabs-fullbleed-tab-color-opacity-disabledleed-tab-color-disabled-opacityinline
Looks like an unintentional find/replace mistake here

2023-01-17 10:31 UTC, alexandereneroth commented on tegel/src/components/tabs/inline-tabs-fullbleed/inline-tabs-fullbleed-theme-vars.scss
>  .sdds-theme-light {
```suggestion
:root,
.sdds-theme-light {
```

2023-01-17 10:33 UTC, alexandereneroth approved these changes

2023-01-17 15:32 UTC, merged