fix(modal): body text spacing
scania-digital-design-system/sdds pull request #779
Opened 2023-01-11 10:00 UTC by theJohnnyMe

**Describe pull-request**  
Fixes for modal:

- body text cut when sticky position of the action bar is set
- padding on right missing on smaller width screen sizes
- enabling control for body text for easier testing
- dropping extra class from story example

**Solving issue**  
Fixes: AB#2849

**How to test**  
1. Go to the Netlify PR link
2. Add a lot of text to the body and see if text display correctly, no matter sticky/static action bar position
3. Check if padding-right on body-text area looks good on all screens

**Additional context**  
In case you are curios to understand the problem better, try running the current master branch and modal, you will see there is an issue with text being cut off when the sticky action bar is set.

2023-01-13 09:40 UTC, alexandereneroth requested changes

2023-01-13 09:40 UTC, alexandereneroth commented on tegel/src/components/modal/modal-native.stories.tsx
> -            <p>
I think we should keep the paragraph element here, it seems like more correct markup. Or at least i think we should add styles so the margins are still correct if you use a paragraph element.

2023-01-13 09:40 UTC, alexandereneroth commented on tegel/src/components/modal/modal-native.stories.tsx
> -    height: 500px;
Nice!

2023-01-13 09:40 UTC, alexandereneroth commented on tegel/src/components/modal/modal-native.stories.tsx
> -            <p>
I could fix this if you prefer

2023-01-13 13:47 UTC, theJohnnyMe commented on tegel/src/components/modal/modal-native.stories.tsx
> -            <p>
Thanks fore review, let me bring it back quickly ;)

2023-01-13 13:56 UTC, theJohnnyMe commented on tegel/src/components/modal/modal-native.stories.tsx
> -            <p>
@alexandereneroth  - Fixed!

2023-01-17 12:22 UTC, alexandereneroth approved these changes
🍨 !

2023-01-17 12:24 UTC, merged