Message rename mode variant
scania-digital-design-system/sdds pull request #785
Opened 2023-01-16 09:20 UTC by EmelieLitwin

**Describe pull-request**  
Renaming the mode variant names to primary/secondary

Should it have a modeVariant prop?

**Solving issue**  
_In case of GitHub issue add # plus the number of the issue (for example #123) OR if it is Azure then AB# and number of ticket_
Fixes: AB#3086

2023-01-16 13:53 UTC, charlottelorensson commented
Warning and Success don't change colors when switching between primary and secondary.

2023-01-19 07:55 UTC, nathalielindqvist approved these changes
Looking good!

2023-01-19 08:20 UTC, mJarsater requested changes
Add changes to migration docs.

2023-01-20 08:03 UTC, mJarsater approved these changes

2023-01-20 10:42 UTC, merged