Textarea mode variant 3118
scania-digital-design-system/sdds pull request #788
Opened 2023-01-18 12:44 UTC by EmelieLitwin

**Describe pull-request**  
Changed mode variant class and added variables for dark mode

**Solving issue**  
Fixes: AB#3119

2023-01-19 07:11 UTC, nathalielindqvist approved these changes
LGTM! 👍

2023-01-19 08:23 UTC, mJarsater commented on tegel/src/components/textarea/textarea.tsx
> +          <span class="sdds-textarea-icon__readonly">
Do we have our own sdds-icon for this?

2023-01-19 08:24 UTC, mJarsater requested changes

2023-01-25 08:17 UTC, mJarsater approved these changes
LGTM! Not really a part of this PR, but should the error state include a error icon before the error text below, like it does in textfield?

2023-01-25 09:36 UTC, EmelieLitwin commented
> LGTM! Not really a part of this PR, but should the error state include a error icon before the error text below, like it does in textfield?

Yes it should 🤔 Excellent spotted. I'll create a separate ticket for it for better traceability

2023-01-25 09:38 UTC, merged