feat(footer): webcomponent
scania-digital-design-system/sdds pull request #807
Opened 2023-01-25 18:19 UTC by mJarsater

**Describe pull-request**  
Webcomponent version of the component. 

### TODO
- [ ] Decide on breakpoints
- [ ] Create slot for custom styling?
- [ ] Add all necessary props to sdds-footer-link (target)

**Solving issue**  
Fixes:AB#3129

**How to test**  
1. Go to storybook link below
2. Check in Components -> Footer -> Web Component
3. Check out the API and check that the styling is correct.

**Screenshots**  

**Additional context**

2023-02-07 12:43 UTC, nathalielindqvist commented on tegel/src/components/footer/webcomponent/sdds-footer.tsx
> +              <p>Scania</p>
Might be a dumb question but why do we have this paragraph tag when we're overwriting it with background-image in SCSS?

2023-02-07 12:45 UTC, mJarsater commented on tegel/src/components/footer/footer-theme-vars.scss
> +  --sdds-footer-top-links-background-hover: var(--sdds-grey-700);
I know. There is some confusion regarding the link in the footer and their states. But I'm onto it 😄

2023-02-07 12:45 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.scss
> +      padding: 19px 40px;
yes, this is based on the native version 👍🏻

2023-02-07 12:46 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer.tsx
> +              <p>Scania</p>
I left this here for accessibility. Not sure of the best way to do it though, but it would have to be represented in clear text somehow 🤔

2023-02-07 15:45 UTC, theJohnnyMe commented on tegel/src/components/footer/webcomponent/sdds-footer.tsx
> +              <p>Scania</p>
@johan-scania  - Here is the implementation of the automatic year switch in the footer as we spoke the other day about it. Nice work Martin!

2023-02-08 10:45 UTC, johan-scania commented on tegel/src/components/footer/webcomponent/sdds-footer.tsx
> +              <p>Scania</p>
Is the year generated in the browser or server side/build time? Just curious.

2023-02-08 10:57 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer.tsx
> +              <p>Scania</p>
That's gonna depend on the framework they are using. If they are using React it will build it on the client (browser). But if they are doing any server side building it's gonna run on build

2023-02-24 08:26 UTC, timrombergjakobsson commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +  shadow: false,
Should we avoid setting this, as shadow as it is false by default?

2023-02-24 08:27 UTC, timrombergjakobsson commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +import { HostElement, State } from '@stencil/core/internal';
```HostElement```import can be removed I think, as it is not used.

2023-02-24 08:30 UTC, timrombergjakobsson commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +              this.open = !this.open;
Just a suggestion, but maybe ```isOpen``` instead?

2023-02-24 08:39 UTC, timrombergjakobsson commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +  parentIsTopPart: boolean = false;
```suggestion
  private isTopPart = false;
  private isRightSlot = false;

  connectedCallback() {
    this.isRightSlot = this.element.parentElement?.slot === 'main-right';
    this.isTopPart = this.element.parentElement?.slot === 'top';
  }

```

2023-02-24 09:19 UTC, timrombergjakobsson commented on tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
> +  render() {
```suggestion
  const { isTopPart, linkHref, target, rel } = this;

    return (
      <div role="listitem" class={isTopPart ? 'top-part-child' : ''}>
        <a href={linkHref} target={target} rel={rel}>
```

2023-02-27 08:37 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +              this.open = !this.open;
I think we have this prop/state as 'open' on a couple of components, so I will leave this one as is for now. Maybe we could have a package-wide decision on how we name these.

2023-02-27 08:39 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +  parentIsTopPart: boolean = false;
Namingwise I feel like parentIsTopPart is closer to what is happening. The actuall link-group can be used both in main footer and top-part and i'ts the parent that decides what is is.

2023-02-27 08:39 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +              console.log(this.open);
Absetotely!

2023-02-27 08:39 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +              console.log(this.open);
```suggestion
```

2023-02-27 08:39 UTC, johan-scania commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +              this.open = !this.open;
"package-wide decision" 👍

2023-02-27 08:41 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
> +  render() {
I think this should be done on all component if we decide thats how we want to structure it. So I'll leave it for now, and we can take a package-wide decision.

2023-02-27 08:41 UTC, mJarsater commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx
> +import { HostElement, State } from '@stencil/core/internal';
It's being used on line 14: https://github.com/scania-digital-design-system/sdds/blob/53bf33aa52b535864c08cdb50e5530a670dfac22/tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.tsx#L14

2023-02-27 16:25 UTC, theJohnnyMe requested changes

2023-02-27 16:25 UTC, theJohnnyMe commented on tegel/src/components/footer/webcomponent/sdds-footer-link-group/sdds-footer-link-group.scss
> +    border-bottom: 1px solid var(--sdds-footer-top-divider);
On mobile view, it seems that text is not in the vertical middle on accordion links: ![Screenshot 2023-02-27 at 17 18 34](https://user-images.githubusercontent.com/17004063/221620067-bcdc7059-5dfd-470f-9f8a-a46e790eed85.png)

To align in test I did this, not sure if you want  to accept it: 
```suggestion
    border-bottom: 1px solid var(--sdds-footer-top-divider);
    align-items: center;
    line-height: inherit;
```

2023-02-28 08:46 UTC, theJohnnyMe commented on tegel/src/components/footer/webcomponent/sdds-footer-link/sdds-footer-link.tsx
> +  /** 'noopener' is a security measure for legacy browsers that preventsthe opened page from getting access to the original page when using target='_blank'. */
```suggestion
  /** 'noopener' is a security measure for legacy browsers that prevents the opened page from getting access to the original page when using target='_blank'. */
```

2023-02-28 08:51 UTC, theJohnnyMe approved these changes
The small spacing issue, in one of readme, I added suggestion there.
All in all, great work buddy 🚀

Please, create another ticket to check dark/light mode switching. Right now colors do not match (or switching does not work), but better to keep it in another PR.

2023-02-28 08:55 UTC, merged