feat(radio button): web component
scania-digital-design-system/sdds pull request #808
Opened 2023-01-26 09:53 UTC by nathalielindqvist

**Describe pull-request**  
Web component version of the radio button component. Also renamed native story to Native.

**Solving issue**  
Fixes: AB#3125

**How to test**  
    1. Go to story book link below
    2. Check in Component -> Radio Button-> Web Component
    3. Check that styling and functionality is correct

**Screenshots**  

**Additional context**

2023-01-30 13:22 UTC, mJarsater requested changes
Really great job! 🚀

Left some thoughts on styling and event handling that we can have a look at together if you want to. Same goes for the comment I left on creating a nice readme with the help of comments on the component props.

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.scss
> +  .sdds-form-input[type='radio']:not(:checked) {
Do we need these psuedo selectors here? Can't it be just `.sdds-form-input[type='radio']`

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.stories.tsx
> +    layout: 'centered',
Make sure to add the generated readme to the 'notes'-tab. See example here: https://github.com/scania-digital-design-system/sdds/blob/main/tegel/src/components/button/button-webcomponent.stories.tsx#L8

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.stories.tsx
> +WebComponent.args = {};
This can be removed

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.stories.tsx
> +Native.args = {};
This can be removed

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.stories.tsx
> +      description: 'Disables the radio buttons.',
Maybe change this to singular, since we are trying to describe one radio button instance.

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +
The props need to have a comment above them, surrounded in `/** {Comment} */`. The comment should be a description of the prop, and will be used be stencil to generate a description in the readme.md file. See example here: https://github.com/scania-digital-design-system/sdds/blob/main/tegel/src/components/button/button-component.tsx#L13 this will lead to a nice looking readme that outlines the componets props, events and so on. See example here: https://deploy-preview-808--tegel-storybook.netlify.app/?path=/info/components-button--web-component

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +        <label class="sdds-form-label" htmlFor={this.radioId}>
I feel like this should be renamed 'sdds-radio-button-label', since it's not really a label for the form. It might not even need a class at all. In the styling you could just target it via its element name instead:
`label {
// styling
}`

2023-01-30 13:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +}
Really nice that you thought of the event! This will only log the message above to the console. We would need to create a custom event and them "emit" it whenever the value for `this.checked` changes. You can have a look at an example here: https://github.com/scania-digital-design-system/sdds/blob/042fa88d689ec37e85009ba2a9f9e06fa3495f9f/tegel/src/components/checkbox/sdds-checkbox.tsx#L32

In the link above on line 31 we are creating a new custom event, then on line 57 we are emitting the event. The emitting of the event is done in the onChange method of the input element, that will pick up any changes to the `this.checked` property.

2023-01-31 12:10 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +    })
This can be moved to the onChange event on the input element above instead. And then in the story you can add an event listener to the document instead, to listen to your exact event. Example here: https://github.com/scania-digital-design-system/sdds/blob/47aa275a14d666200033da6afeea967ea962ee51/tegel/src/components/checkbox/sdds-checkbox.stories.tsx#L58

2023-01-31 12:11 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +        disabled={this.disabled} />
Here you can add a onChange listener
```suggestion
        disabled={this.disabled}
        onChange={() => {
        this.sddsRadioButtonChangeEvent.emit({
           radioId: this.radioId,
           checked: this.checked,
        })
        }}
        />
```

2023-01-31 12:14 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +        disabled={this.disabled} />
Maybe we should add the value as part of the object that's passed to the event also. 

`        this.sddsRadioButtonChangeEvent.emit({
           radioId: this.radioId,
           checked: this.checked,
           value: this.value
        })`

2023-02-06 07:17 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +  @Prop() ariaDescribedBy: string;
Let's try and align on these across all component before we merge anything.

2023-02-06 07:19 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +  @Prop() radioId: string;
I think we can set this one to a default value if the user doesn't specify it, see example: https://github.com/scania-digital-design-system/sdds/blob/main/tegel/src/components/toggle/sdds-toggle.tsx#L38

2023-02-06 07:20 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +  /** Sends unique radio button identifier and status when it is checked. */
When we add the default value for the radio-id, we should specify in this comment that if no ID is specified a random one will be generated and if they want to listen to the event they should not use the randomly generated one.

2023-02-06 07:20 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.stories.tsx
> +  export const Native = Template.bind({});
🚀

2023-02-06 07:22 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.stories.tsx
> +  <script>
Maybe add a comment above the script tag here to highlight that it's there for demo purposes. See example: https://github.com/scania-digital-design-system/sdds/blob/main/tegel/src/components/toggle/sdds-toggle.stories.tsx#L88

2023-02-15 10:14 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button.tsx
> +  @Prop() ariaDescribedBy: string;
For now: I would suggest we grad these from the host element, example: 
https://github.com/scania-digital-design-system/sdds/blob/main/tegel/src/components/toast/sdds-toast.tsx#L107

2023-02-20 12:49 UTC, mJarsater requested changes
Small this on the label in disabled state, otherwise LGTM!

2023-02-20 12:49 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.scss
> +        color: var(--sdds-grey-600);
I think this should be changed to be a variable instead. From what I could see in Figma the label has grey-600 in light mode and grey-400 in dark (when disabled).

2023-02-20 12:51 UTC, mJarsater commented on tegel/src/components/radio-button/radio-button-component.scss
> +        color: var(--sdds-grey-600);
So I would suggest adding a: --sdds-radio-button-color-disabled variable and setting it's values based on the theme.

2023-02-20 14:49 UTC, timrombergjakobsson approved these changes

2023-02-20 15:04 UTC, mJarsater approved these changes
Noice! 🧁

2023-02-20 15:08 UTC, merged