fix: Standardise Storybook controls
scania-digital-design-system/sdds pull request #815
Opened 2023-01-31 12:46 UTC by nathalielindqvist

**Describe pull-request**  
An attempt to standardise the Storybook controls in all available components. Also updated control descriptions, added default values to controls and re-structured deprecated control types. Also some minor various fixes that were found along the way.  

**Solving issue**  
Fixes: AB#2696

**How to test**  
_Add description how to test if possible_
1. Go to Storybook through the link below.
2. Check order of controls and descriptions of all components.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

**Screenshots**  

**Additional context**

2023-02-03 13:52 UTC, mJarsater commented on tegel/src/components/accordion/accordion.stories.tsx
> +        defaultValue: { summary: 'false' },
Would be good if we could align this. Im thinking this should always be 'Inherit from parent'. We also need to make sure that this prop is by default set to null in the component.

2023-02-03 13:54 UTC, mJarsater commented on tegel/src/components/badge/badge.stories.tsx
> +        defaultValue: { summary: false },
This should be 'true'. Also the components prop is now called 'isVisible', this should be changed to 'visibile' but maybe in another PR, and the change also needs to be added to the migration docs.

2023-02-03 13:56 UTC, mJarsater commented on tegel/src/components/button/button-webcomponent.stories.tsx
> +      description: 'Sets a fluid width in certain components.',
I think this could be changed to 'Sets a fluid width on the component.'

2023-02-03 14:00 UTC, mJarsater commented on tegel/src/components/card/card.stories.tsx
> +        type: 'text',
Nice 🧁

2023-02-06 08:30 UTC, nathalielindqvist commented on tegel/src/components/badge/badge.stories.tsx
> +        defaultValue: { summary: false },
Ticket written for prop update, will update default value in this PR

2023-02-06 08:43 UTC, nathalielindqvist commented on tegel/src/components/accordion/accordion.stories.tsx
> +        defaultValue: { summary: 'false' },
Handled in another PR

2023-02-06 08:54 UTC, mJarsater commented on tegel/src/components/data-table/native-table.stories.tsx
>          ${args.dividers ? 'sdds-table--divider' : ''}
I think we can desctructure the arg here instead of having to access it via 'args.*' everywhere.

2023-02-06 08:58 UTC, mJarsater commented on tegel/src/components/datetime/datetime.stories.tsx
> +      },
Maybe change this to a text input instead. Same for helper text.

2023-02-06 08:59 UTC, mJarsater commented on tegel/src/components/datetime/datetime.stories.tsx
> +      ${noMinWidth ? 'no-min-width' : ''}
🧁

2023-02-06 09:00 UTC, mJarsater commented on tegel/src/components/divider/divider.stories.tsx
> +          summary: '150',
Not sure the divider has a defaultValue of  150px? I think it will always be 100%. So I would suggest removing the defaultValue completely for this

2023-02-10 12:09 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.tsx
> +    },
I think this could be a boolean instead. Just error - yes or no.

2023-02-10 12:10 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.tsx
> +          summary: 'Large',
This should reflect the prop and it's default value, so in this case it should be 'lg'

2023-02-10 12:10 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.tsx
> +          summary: 'Auto',
Since it should reflect the prop this should be lower case - 'auto'

2023-02-10 12:11 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-filter/dropdown-filter.stories.tsx
> +      },
This can be removed. The component does not have any default value for this prop.

2023-02-10 12:12 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
> +    },
I think this could be a boolean instead. Just error - yes or no.

2023-02-10 12:12 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-native.stories.tsx
> +      },
I think this could be a boolean instead. Just error - yes or no.

2023-02-10 12:12 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
> +          summary: 'Large',
```suggestion
          summary: 'lg',
```

2023-02-10 12:12 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
> +          summary: 'Auto',
```suggestion
          summary: 'auto',
```

2023-02-10 12:13 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
> +        },
This can be removed. The component does not have any default value for this prop.

2023-02-10 12:13 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-default.stories.tsx
> +          summary: 'None',
```suggestion
          summary: 'none',
```

2023-02-10 12:14 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-wc-multiselect.stories.tsx
>      ],
I think a lot of the stuff in the dropdown can be fixed once version 3 is merged, otherwise you might fix something that's gonna be removed anyway.

2023-02-10 12:16 UTC, mJarsater commented on tegel/src/components/message/message.stories.tsx
> +      options: ['Primary', 'Secondary'],
I think we should include the inherit from parent option

2023-02-10 12:17 UTC, mJarsater commented on tegel/src/components/message/message.stories.tsx
> +          summary: 'Information',
I think this can be lowercase, to reflect the prop value.

2023-02-10 12:17 UTC, mJarsater commented on tegel/src/components/modal/modal-native.stories.tsx
> +          summary: 'Large',
```suggestion
          summary: 'lg',
```

2023-02-10 12:19 UTC, mJarsater commented on tegel/src/components/modal/modal.tsx
> +  @Prop() show: boolean = false;
This needs a comment above it. Descibing the prop, to be displayed in the readme.

2023-02-10 12:19 UTC, mJarsater commented on tegel/src/components/popover-canvas/popover-canvas.stories.tsx
> +          summary: 'Bottom',
```suggestion
          summary: 'bottom',
```

2023-02-10 12:20 UTC, mJarsater commented on tegel/src/components/popover-menu/popover-menu-icons.stories.tsx
> +          summary: 'Bottom start',
```suggestion
          summary: 'bottom start',
```

2023-02-10 12:20 UTC, mJarsater commented on tegel/src/components/popover-menu/popover-menu.stories.tsx
> +          summary: 'Bottom start',
```suggestion
          summary: 'bottom start',
```

2023-02-10 12:20 UTC, mJarsater commented on tegel/src/components/spinner/spinner.stories.tsx
> +export const WebComponent = Template.bind({});
```suggestion
export const WebComponent = Template.bind({});


```

2023-02-10 12:26 UTC, mJarsater requested changes
Great job! 🧁

Some minor stuff. But overall I think we should aspire to have default values that is aligned with the actual prop. For example: size, almost all component have a default size of 'lg', then we should write that in storybook. Even though the controls might have Large as the option

2023-02-15 15:04 UTC, nathalielindqvist commented on tegel/src/components/spinner/spinner.stories.tsx
> +export const WebComponent = Template.bind({});
Think this was handled in another PR or when rebasing

2023-02-16 15:48 UTC, closed without merging