fix: mode variant add null and inherit from parent to components
scania-digital-design-system/sdds pull request #821
Opened 2023-02-09 08:28 UTC by EmelieLitwin

**Describe pull-request**  
Card, message, textfield and textarea was missing null option to mode variant and/or Inherit from parent as option in storybook

**How to test**  
Check the components and that mode variants working in storybook and looks ok in code

2023-02-09 16:02 UTC, charlottelorensson commented
<img width="305" alt="Skärmavbild 2023-02-09 kl  16 48 09" src="https://user-images.githubusercontent.com/92715317/217863772-4bf5b223-20f2-4962-bc0d-8f6d3c0a4eb4.png">

Perhaps not the place (and perhaps won't be so visible) but just something I noticed, it looks like the web component has blue lines on the corners.

And it seems like the font color in the textfields are not aligned with Figma:

<img width="636" alt="Skärmavbild 2023-02-09 kl  17 00 10" src="https://user-images.githubusercontent.com/92715317/217867041-2f08974a-3079-41b0-8cd0-815415ad2138.png">


But the mode variants seem to be working fine! :)

2023-02-09 16:03 UTC, charlottelorensson commented
Forgot to mention that the first image was the message component* :)

2023-02-10 09:54 UTC, mJarsater commented on tegel/src/components/textarea/textarea.tsx
> +  @Prop() modeVariant: 'primary' | 'secondary' | null = null;
```suggestion
  @Prop() modeVariant: 'primary' | 'secondary' = null;
```

2023-02-10 09:54 UTC, mJarsater commented on tegel/src/components/message/sdds-message.tsx
> +  @Prop() modeVariant: 'primary' | 'secondary' | null = null;
```suggestion
  @Prop() modeVariant: 'primary' | 'secondary' = null;
```

2023-02-10 09:56 UTC, mJarsater requested changes
Nice 🚀! I think we can remove the optional null value on the modeVariant prop. Then it won't show in the readme and Im guessing we don't really want people to have to care about this.

2023-02-10 16:09 UTC, EmelieLitwin commented
> Nice 🚀! I think we can remove the optional null value on the modeVariant prop. Then it won't show in the readme and Im guessing we don't really want people to have to care about this.

Good feedback! If that's something you think we should do, it should be done on all components!

2023-02-10 16:12 UTC, mJarsater commented
> > Nice 🚀! I think we can remove the optional null value on the modeVariant prop. Then it won't show in the readme and Im guessing we don't really want people to have to care about this.
> 
> Good feedback! If that's something you think we should do, it should be done on all components!

Yeah that makes sense to me. Then all components with a modeVariant would have:
`@Prop() modeVariant: 'primary' | 'secondary' = null;`

2023-02-13 12:19 UTC, EmelieLitwin commented
> <img alt="Skärmavbild 2023-02-09 kl 16 48 09" width="305" src="https://user-images.githubusercontent.com/92715317/217863772-4bf5b223-20f2-4962-bc0d-8f6d3c0a4eb4.png">
> 
> Perhaps not the place (and perhaps won't be so visible) but just something I noticed, it looks like the web component has blue lines on the corners.
> 
> And it seems like the font color in the textfields are not aligned with Figma:
> 
> <img alt="Skärmavbild 2023-02-09 kl 17 00 10" width="636" src="https://user-images.githubusercontent.com/92715317/217867041-2f08974a-3079-41b0-8cd0-815415ad2138.png">
> 
> But the mode variants seem to be working fine! :)

What is he problem with the textfield? In dark mode the inside label is grey-400 and placeholder grey-600, looks like it's the same in figma?

2023-02-15 14:34 UTC, mJarsater approved these changes
LGTM!

2023-02-15 15:00 UTC, merged