fix(table): refactor event names
scania-digital-design-system/sdds pull request #844
Opened 2023-02-17 13:17 UTC by mJarsater

**Describe pull-request**  
Refactored event names and updated story. 

**Solving issue**  
Fixes: AB#3361

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Data Table -> Check all web component stories
3. Check the readme and event names to make sure they conform with convention.
4. Check if there are any events that are marked as internal now that should be external, and vice versa.
5. Check the event names. Since some event are so specific to this component I had to digress a bit from the naming convention.. 😢 

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-02-17 13:30 UTC, mJarsater commented on tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
> +  internalSddsChangeListener(event: CustomEvent<internalSddsChange>) {
should this be `internalSddsPropsChange` instead?

2023-02-17 15:52 UTC, mJarsater commented on tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
> +  internalSddsChangeListener(event: CustomEvent<internalSddsChange>) {
Starting to feel like it could be a good idea to bind internal events to the component, e.g.`internalSddsTablePropChange`

2023-03-06 15:43 UTC, alexandereneroth requested changes

2023-03-07 07:45 UTC, mJarsater commented on tegel/src/components/data-table/table-footer/table-footer.tsx
> +    eventName: 'sddsPaginationChange',
I'll go with sddsPageChange. Feel like it short and sweet and still does the work 😄

2023-03-07 08:24 UTC, mJarsater commented on tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
> -  // Listen to textAlignEvent from data-table-header-element
I will keep the textAlign event for now. It has some things that the propschangeevent does not. The column key, also it is not set on the top component as the other props that are controlled in the propschangeevent are.

2023-03-07 16:31 UTC, alexandereneroth commented on tegel/src/components/data-table/table-body-cell/table-body-cell.tsx
> -const relevantTableProps: TablePropsChangedEvent['changed'] = [
What do you think of calling this `internalSddsTablePropChange`, since it contains a tableId (which means its not a generic change event)?

2023-03-09 15:36 UTC, alexandereneroth approved these changes
Nice work! 🥷

2023-03-09 15:40 UTC, merged