feat(events - textfield/textarea): updated events for textfield/textarea
scania-digital-design-system/sdds pull request #850
Opened 2023-02-20 16:06 UTC by mJarsater

**Describe pull-request**  
Updated the focus/blur/input/change event for the textfield/textarea.

**Solving issue**  
Fixes: #767

**How to test**  
1. Check out the branch
2. Run npm run storybook for components
3. Check the readme

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-03-06 16:22 UTC, alexandereneroth requested changes

2023-03-06 16:22 UTC, alexandereneroth commented on components/src/components/textarea/textarea.tsx
> -  customChange: EventEmitter;
Changing the event name here would be a breaking change, maybe cancelable shouldn't be changed as well for the same reason, although i admit i'm not sure what its for here.

If we keep custom change here, then i think the other events could also follow the "customSomething" naming pattern

2023-03-06 16:22 UTC, alexandereneroth commented on components/src/components/textarea/textarea.tsx
> +      this.sddsFocus.emit(event);
I don't think this method is needed since the textarea already has a onFocus on it. Id move the focusInput=true and emit focus inside there instead.

2023-03-07 16:50 UTC, alexandereneroth requested changes

2023-03-07 16:50 UTC, alexandereneroth commented on components/src/components/textarea/readme.md
> +| `sddsBlur`     | Blur event for the textarea   | `CustomEvent<FocusEvent>` |
IMO its better with a bad name as long as its consistent, so I'd use customBlur, customFocus, etc here.
Then we improve our users chances of learning the API, and improve readability

2023-03-07 16:50 UTC, alexandereneroth commented on components/src/components/textarea/textarea.tsx
> +    cancelable: false,
Are you sure this change is not breaking the API in some way?

2023-03-07 16:50 UTC, alexandereneroth commented on components/src/components/textfield/textfield.tsx
> +        <div onClick={() => this.textInput.focus()} class="sdds-textfield-container">
In my limited testing, this focus() call did not seem to be needed.

2023-03-07 16:50 UTC, alexandereneroth commented on components/src/components/textfield/textfield.tsx
> +    console.log('hej');
```suggestion
```

2023-03-08 07:20 UTC, mJarsater commented on components/src/components/textarea/textarea.tsx
> +    cancelable: false,
Yes, since we are not checking for any cancelation. But since it's not really visible I can remove it.

2023-03-08 07:25 UTC, mJarsater commented on components/src/components/textarea/readme.md
> +| `sddsBlur`     | Blur event for the textarea   | `CustomEvent<FocusEvent>` |
Agree! Will rename the other events

2023-03-08 07:43 UTC, timrombergjakobsson commented on components/src/components/textfield/textfield.tsx
> +  handleInput(event): void {
Just a question, but don't we want to update the value before emitting? To mitigate that the value could be out of sync? Just thinking out loud.
```suggestion
  this.value = event.target.value;
  this.sddsInput.emit(event);
```

2023-03-08 07:44 UTC, mJarsater commented on components/src/components/textfield/textfield.tsx
> +  handleInput(event): void {
Absolutely!

2023-03-08 12:59 UTC, alexandereneroth approved these changes
🎖️

2023-03-08 13:13 UTC, merged