AB#444 Feature/tooltip
scania-digital-design-system/sdds pull request #86
Opened 2021-03-02 10:55 UTC by iths-jonathan-engman

**Describe pull-request**  
--Tooltip component with control for changing the borders, also with the default state.
--Including adding custom text.
--Sizeing is correctly responsive.

**How to test**  
Tooltip -> basic.

**Additional context**  
This is the basic design based on the mockup. No Javascript functionality and/or hover.

2021-03-02 13:39 UTC, niklasros commented
Is it possible to get an example in Storybook on how the transition fade-in/out looks like when hovering an element that triggers a tooltip? Would be great to have that defined, like a default quick fade-in/out transition for all tooltips.

2021-03-02 14:24 UTC, iths-jonathan-engman commented
> Is it possible to get an example in Storybook on how the transition fade-in/out looks like when hovering an element that triggers a tooltip? Would be great to have that defined, like a default quick fade-in/out transition for all tooltips.

Commenting this for transparency.
I talked to Niklas regarding the comment, and he wishes to see a live example of a working tooltip attached to a element.

2021-03-03 15:17 UTC, helloimela commented on components/src/components/tooltips/tooltip.tsx
> +export class Tooltips {
A single component, Class should be named Tooltip. And to be consistent with tag name as well

2021-03-04 14:41 UTC, niklasros commented
I think we need to change the structure a bit for the tooltip.

**Option Basic** 
The possibility to render all the tooltip types (as your previous solution)

**Option Transition**
Example of how the tooltip is animated in. On this option, it's enough to only show one tooltip type. As it is now, it's a bit confusing since the hover can show all the types, and then positions the tooltip in the wrong place.

<img width="165" alt="tooltip-hover-example" src="https://user-images.githubusercontent.com/59045455/109979543-4d47fc00-7cff-11eb-836d-3986219609fe.png">

2021-03-04 14:41 UTC, niklasros commented
Add a quick fade-in transition for the tooltip, so that the transition becomes a bit softer.

2021-03-05 07:19 UTC, helloimela commented on components/src/components/tooltips/tooltip.stories.js
> +  <div class="target-wrap">
Try to avoid your own styling on target element and use sdds component such as sdds-button to be used as an example in storybook

2021-03-05 07:25 UTC, helloimela commented on components/src/components/tooltips/tooltip.scss
> +  top: 20rem;
If looking at the UI guidelines in Figma & in the site, the distance between tooltip and the target is 8px, so top value should be 2rem.
Try to use sdds spacing element css variable for all spacing values. If it is not available in the spacing tokens, then you can fill in your own value. **var(--sdds-spacing-element-xxx)**

2021-03-05 07:27 UTC, helloimela commented on components/src/components/tooltips/tooltip.scss
> +  left: 32rem;
left position will vary depends on the position of the tooltip. Might be set from the script not from the css, so, maybe add a 0 value in the css, to normalize its position

2021-03-08 07:37 UTC, niklasros commented
The tooltip is currently behind a button by default, so I can not preview it.

<img width="154" alt="tooltip" src="https://user-images.githubusercontent.com/59045455/110289221-67c4f280-7fe9-11eb-951b-157de92de1c8.png">

2021-03-12 10:46 UTC, iths-jonathan-engman commented
Todo:
--Transition(s)
--Fix small issues in positioning
--Remove border option in Storybook

2021-03-16 07:51 UTC, helloimela requested changes

2021-03-16 07:51 UTC, helloimela commented on package.json
> +    "@popperjs/core": "^2.9.1"
popper.js is a dependency to components package, should be installed inside components/ folder. Dependency should be added in sdds/components/package.json

2021-03-16 08:12 UTC, mmexvr commented on components/src/components/tooltips/tooltip.tsx
> +      // popperInstance.setOptions({
Remove unused code

2021-03-16 08:50 UTC, helloimela requested changes

2021-03-16 08:50 UTC, helloimela commented on package.json
> +  "dependencies": {}
Remove unused properties from code changes

2021-03-16 09:18 UTC, helloimela approved these changes

2021-03-17 15:14 UTC, niklasros commented
Do we need all these types of positions in the storybook example? The idea of the different styles of the tooltip is that a specific style should be used depending on where the component is placed. Is it placed or instance in a top left corner, we show this by having the hard corner on the left side of the tooltip.

I've tried to explain in the image below how I see the different usage needs, but I might be missing something!

<img width="340" alt="tooltip-positions" src="https://user-images.githubusercontent.com/59045455/111490757-935b8180-873b-11eb-9240-3832947e5322.png">

2021-03-18 08:12 UTC, helloimela commented
> Do we need all these types of positions in the storybook example? The idea of the different styles of the tooltip is that a specific style should be used depending on where the component is placed. Is it placed or instance in a top left corner, we show this by having the hard corner on the left side of the tooltip.
> 
> I've tried to explain in the image below how I see the different usage needs, but I might be missing something!
> 
> <img alt="tooltip-positions" width="340" src="https://user-images.githubusercontent.com/59045455/111490757-935b8180-873b-11eb-9240-3832947e5322.png">

@niklasros Yes, from a development perspective, we need to define a speicific value to make the component understand which corner should be border-radius=0 when in a specific position.

2021-03-18 12:14 UTC, niklasros commented
> > Do we need all these types of positions in the storybook example? The idea of the different styles of the tooltip is that a specific style should be used depending on where the component is placed. Is it placed or instance in a top left corner, we show this by having the hard corner on the left side of the tooltip.
> > I've tried to explain in the image below how I see the different usage needs, but I might be missing something!
> > <img alt="tooltip-positions" width="340" src="https://user-images.githubusercontent.com/59045455/111490757-935b8180-873b-11eb-9240-3832947e5322.png">
> 
> @niklasros Yes, from a development perspective, we need to define a speicific value to make the component understand which corner should be border-radius=0 when in a specific position.

Ok! Still, some of the visualizations for me are still wrong in a sense. For instance, when using the bottom-right-corner the tooltip shouldn't be placed like that. But if it make sense from a development point of view, lets go with it!

<img width="291" alt="tooltip_example" src="https://user-images.githubusercontent.com/59045455/111624100-8f873800-87eb-11eb-922a-283b6ea2a37f.png">

2021-03-18 12:14 UTC, niklasros approved these changes

2021-03-19 08:04 UTC, merged