fix(textfield/textarea): scope css
scania-digital-design-system/sdds pull request #861
Opened 2023-02-22 14:39 UTC by mJarsater

**Describe pull-request**  
Scoped css and removed class name creation in render method.

**Solving issue**  
Fixes: -

**How to test**  
1. Go to storybook link below
2. Check in Components -> Textfield/Textarea
3. Check that the styling is still correct.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-02-23 07:49 UTC, EmelieLitwin commented
Textarea in secondary mode variant:
![image](https://user-images.githubusercontent.com/22123579/220849152-c427e728-cc46-4149-bb8f-49f9d40a0873.png)

Textfield:
![image](https://user-images.githubusercontent.com/22123579/220849257-591d9812-1e0c-46fb-b4b0-af37689bc384.png)

2023-02-23 09:22 UTC, mJarsater commented
> Textarea in secondary mode variant: ![image](https://user-images.githubusercontent.com/22123579/220849152-c427e728-cc46-4149-bb8f-49f9d40a0873.png)
> 
> Textfield: ![image](https://user-images.githubusercontent.com/22123579/220849257-591d9812-1e0c-46fb-b4b0-af37689bc384.png)

Nice! Missed to import the css vars globally. Should be fixed now 🎨

2023-02-28 08:26 UTC, EmelieLitwin requested changes
Something off with the label styling:
![image](https://user-images.githubusercontent.com/22123579/221796017-f51e5d83-7560-4bfe-9f38-28f6234ae685.png)

In main:
![image](https://user-images.githubusercontent.com/22123579/221795933-0f3f026c-2c5e-4035-b3cf-484aa762bb4c.png)

2023-02-28 08:39 UTC, mJarsater commented
> Something off with the label styling: ![image](https://user-images.githubusercontent.com/22123579/221796017-f51e5d83-7560-4bfe-9f38-28f6234ae685.png)
> 
> In main: ![image](https://user-images.githubusercontent.com/22123579/221795933-0f3f026c-2c5e-4035-b3cf-484aa762bb4c.png)

Nice catch, should be fixed now! 😄

2023-03-07 16:59 UTC, alexandereneroth approved these changes
Looks like an improvement 🍰

2023-03-08 07:34 UTC, merged