fix(datetime): event name update
scania-digital-design-system/sdds pull request #862
Opened 2023-02-23 09:58 UTC by theJohnnyMe

## **Describe pull-request**  
Events name update

## **Solving issue**  
Fixes: AB#3358

## **How to test**  
1. Go to the Netlify Storybook link
2. Check if events are firing on click/focus/blur 
3. Check if code looks OK

## **Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

## **Additional context**  
Work-related to ShadowDOM and some more improvements of this component I will do it in another PR. To keep PR slim and easy to review. I suggest going over commits to easily follow up what was happening.

2023-02-23 11:55 UTC, mJarsater commented on tegel/src/components/datetime/datetime.tsx
> +  sddsBlur: EventEmitter;
```suggestion
  sddsBlur: EventEmitter<FocusEvent>;
```
Just to be extra clear to the user we could type this as a FocusEvent

2023-02-23 11:55 UTC, mJarsater commented on tegel/src/components/datetime/datetime.tsx
> +    cancelable: true,
```suggestion
    cancelable: false,
```

2023-02-23 11:57 UTC, mJarsater commented on tegel/src/components/datetime/datetime.tsx
> +              autoFocus={this.autofocus}
```suggestion
              autofocus={this.autofocus}
```

2023-02-23 11:58 UTC, mJarsater requested changes
Nice stuff! Left some minor comments 🧁

2023-02-23 14:16 UTC, theJohnnyMe commented on tegel/src/components/datetime/datetime.tsx
> +              autoFocus={this.autofocus}
Nice catch ;)

2023-02-23 14:54 UTC, theJohnnyMe commented on tegel/src/components/datetime/datetime.tsx
> +    cancelable: true,
Thanks again for reflecting on this one, good catch and good thinking ;)

2023-02-23 15:09 UTC, theJohnnyMe commented on tegel/src/components/datetime/datetime.tsx
> +  }
Good call, changes done!

2023-02-23 15:10 UTC, theJohnnyMe commented
Review changes applied, ready for another round of review :)

2023-02-28 12:05 UTC, mJarsater approved these changes
LGTM! Nice 🚀

2023-03-01 15:00 UTC, merged