Feat/3336 divider
scania-digital-design-system/sdds pull request #879
Opened 2023-03-02 13:37 UTC by timrombergjakobsson

**Describe pull-request**  
Web component version of the Divider. The component has a horizontal and vertical version, the horizontal being an hr element as it represents a thematic break. The vertical version of the divider is a normal div. The horizontal divider has width prop to be set and the vertical version a height prop. Both version comes with a light and dark counterpart. 

**Solving issue**  
Fixes:[AB#3336](https://dev.azure.com/scaniadigitaldesignsystem/Tegel/_sprints/taskboard/Design%20Tools%20and%20Systems/Tegel/Sprint%2052%20-%20IWD?workitem=3336)

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Divider, Web Component
Test the controls and check the API.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Direction, vertical and horizontal version

2023-03-02 18:17 UTC, timrombergjakobsson commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=scania-digital-design-system_sdds&pullRequest=879)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879) No Coverage information [![13.6%](https://camo.githubusercontent.com/efef8d7f6abcfdf5c67f93cc5bf65fa6c176ccbc2b89d16309748853e95b3863/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f32302d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list) [13.6% Duplication](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list)

This code duplication error feels a bit off.

2023-03-03 07:30 UTC, mJarsater commented
> > SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=scania-digital-design-system_sdds&pullRequest=879)
> > [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL)
> > [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879) No Coverage information [![13.6%](https://camo.githubusercontent.com/efef8d7f6abcfdf5c67f93cc5bf65fa6c176ccbc2b89d16309748853e95b3863/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f32302d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list) [13.6% Duplication](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list)
> 
> This code duplication error feels a bit off.

Yep, I would suggest just ignoring it for now. Do you want feedback on this PR straight away or should we wait until you've removed the under construction tag? 😄

2023-03-03 07:44 UTC, timrombergjakobsson commented
> > > SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=scania-digital-design-system_sdds&pullRequest=879)
> > > [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL) [0 Code Smells](https://sonarcloud.io/project/issues?id=scania-digital-design-system_sdds&pullRequest=879&resolved=false&types=CODE_SMELL)
> > > [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879) No Coverage information [![13.6%](https://camo.githubusercontent.com/efef8d7f6abcfdf5c67f93cc5bf65fa6c176ccbc2b89d16309748853e95b3863/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f32302d313670782e706e67)](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list) [13.6% Duplication](https://sonarcloud.io/component_measures?id=scania-digital-design-system_sdds&pullRequest=879&metric=new_duplicated_lines_density&view=list)
> > 
> > 
> > This code duplication error feels a bit off.
> 
> Yep, I would suggest just ignoring it for now. Do you want feedback on this PR straight away or should we wait until you've removed the under construction tag? 😄

Go ahead with the slaughtering, I mean feedback.

2023-03-03 07:48 UTC, mJarsater commented on tegel/src/components/divider/divider-component.scss
> +@import './divider-theme-vars.scss';
This can be imported in globals/global.scss instead. By importing it there we can set css variables based on mode of a higher lever (outside of the component), and in that way the user would only have to specify the theme once. On body/app for instance.

2023-03-03 07:49 UTC, mJarsater commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +        defaultValue: { summary: 'Horizontal' },
To align with the prop name I think we should say default value is 'horizontal' (lowercase).

2023-03-03 07:52 UTC, mJarsater commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +    theme: {
The theme needs to not be set in individual component. It should be set on the document. There is a switch in storybook that changes dark/light mode by toggling the class on the body (sdds-mode-light/sdds-mode-dark).

2023-03-03 07:52 UTC, mJarsater commented on tegel/src/components/divider/divider.spec.ts
> +});
Great initiative!

2023-03-03 07:53 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +  @Prop() direction: 'horizontal' | 'vertical' = 'horizontal';
Nice!

2023-03-03 07:54 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +    theme: {
Maybe a misunderstanding, but the theme here, is merely the dark light version of the divider, aka color change. So not dark light mode. Or am I misunderstanding what you mean?

2023-03-03 07:55 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +
Not sure these needs to be props. Im thinking that if the divider is horizontal it should have a 1px height and 100% width, and if it's vertical it should have 1px width and 100% height. With that the divider adapts to its parent and the user wont have to specify and widht/height based on what direction they have specified.

2023-03-03 07:58 UTC, mJarsater commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +    theme: {
Ah alright! I think it would have to be checked with a designer (maybe @EmelieLitwin  could help here), whether or not that property in Figma is tied to the component or not. Based on how it is in other components the theme property in Figma is a representation of the overall theme and not the theme of the individual component.

2023-03-03 07:58 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +
> Not sure these needs to be props. Im thinking that if the divider is horizontal it should have a 1px height and 100% width, and if it's vertical it should have 1px width and 100% height. With that the divider adapts to its parent and the user wont have to specify and widht/height based on what direction they have specified.

Yes I agree, a first version was like that then I changed. It could all be controlled from css?

2023-03-03 07:59 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +
Yeah, that's what I'm think also! 🚀

2023-03-03 08:00 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-component.scss
> +    box-sizing: border-box;
> We have a mixin for this, not that it makes any real difference. Just an FYI

Just for the ```box-sizing: border-box```?

2023-03-03 08:00 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +        {label && <span {...labelProps}>{label}</span>}
Is a label needed here? It's not part the design right?

2023-03-03 08:02 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +    theme: {
> Ah alright! I think it would have to be checked with a designer (maybe @EmelieLitwin could help here), whether or not that property in Figma is tied to the component or not. Based on how it is in other components the theme property in Figma is a representation of the overall theme and not the theme of the individual component.

Ok cos right now in current "Native" version of the divider there is a dark, light and colored version. And as I understood, the new web component should only have the dark/light variant. But yes, @EmelieLitwin by all means, some feedback!!

2023-03-03 08:03 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +      'role': 'separator',
Since it's always gonna be a separator, could we just set this on the host element in the return straight away instead. I think this is a nice way of building up to the return, it's just different to how we have done it in other component. We have tried to use stencils lifecycle to to add/change/remove properties based on other properties or other stuff that might impact the component.

2023-03-03 08:05 UTC, mJarsater commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +    theme: {
Awesome, then I guess either its:

- Each mode (site-wide) has a certain look, either dark or light
or
- The component has a two mode variant for each site-wide mode

2023-03-03 08:05 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-component.scss
> +@import './divider-theme-vars.scss';
Ah ok, was not aware, you mean here then?
![Skärmavbild 2023-03-03 kl  09 05 01](https://user-images.githubusercontent.com/201671/222665547-20ebab9c-9265-43a9-a419-23d37d655893.png)

2023-03-03 08:07 UTC, mJarsater commented on tegel/src/components/divider/divider-component.scss
> +    box-sizing: border-box;
Haha yep. My thinking is that we could remove that mixin, but then create a css-reset-mixin that can be imported in all components, that does this and what ever else we want. This to get around the fact the the global styling wont penetrate the shadowDOM, so it would have to be done on all components (that use shadowDOM.)

2023-03-03 08:07 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +        {label && <span {...labelProps}>{label}</span>}
Hm your right. Prob something that is not needed. I will have a look!

2023-03-03 08:08 UTC, mJarsater commented on tegel/src/components/divider/divider-component.scss
> +@import './divider-theme-vars.scss';
Yeah exactly! That way we have all the css variables globally, and the neat thing is that they go through the shadowDOM. So with this we are much more flexible in light/dark mode

2023-03-03 08:09 UTC, mJarsater reviewed
Really great stuff, love the test spec!

2023-03-03 08:10 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-component.scss
> +    box-sizing: border-box;
> Haha yep. My thinking is that we could remove that mixin, but then create a css-reset-mixin that can be imported in all components, that does this and what ever else we want. This to get around the fact the the global styling wont penetrate the shadowDOM, so it would have to be done on all components (that use shadowDOM.)

Sounds like a good idea, but in a separate pr I suggest then! Should I use the mixin here for consistency? This one I guess it is ```@include sdds-box-sizing;```?

2023-03-03 08:20 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +      'role': 'separator',
I see, so something like this instead:
```suggestion
      return (
          <Host
            role="separator"
            aria-orientation={this.direction === 'vertical' ? 'vertical' : undefined}
            class={`sdds-divider ${this.direction} ${colorClass}`}
            style={{
              width: this.direction === 'horizontal' && this.width,
              height: this.direction === 'vertical' && this.height,
            }}
          >
            {label && <span class="sdds-divider-label" aria-hidden>{label}</span>}
            {this.direction === 'horizontal' ? <hr style={{width: '1px', height: '1px'}} /> : <div style={{width: '1px', height: '1px'}} />}
          </Host>
     );
```

But without the width height props maybe and the label then?

2023-03-03 10:52 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +      'role': 'separator',
Yeah exactly, nice!

2023-03-07 09:19 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
I would recommend changing this to an enum instead. That way they both can't be true/false at the same time.

2023-03-07 09:26 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
Ah yea, I like that:
```suggestion
 enum DividerColor {
  Light = 'light',
  Dark = 'dark',
}

2023-03-07 09:28 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +    }
Yes, I see what you mean, I thought as it was already defined in the scss-file that it was the convention to follow. I will refactor and see what we can get from it.

2023-03-07 09:28 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
Yep! You could do it just one line also: 
```suggestion
  /** Sets the divider to light version */
  @Prop() type: 'light' | 'dark' = 'light'
```

2023-03-07 09:28 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
This would set the type to light by default

2023-03-07 09:29 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
Sure, same as direction.

2023-03-07 09:30 UTC, mJarsater commented on tegel/src/components/divider/divider.tsx
> +  @Prop() dark: boolean = false;
Yeah exactly 🚀

2023-03-08 08:27 UTC, mJarsater commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +import { formatHtmlPreview } from '../../utils/utils';
Great stuff! It doesn't seem like the test are using the web component though? I would recommend creating two story files, one for the HTML/CSS component and one for the web component, and then control the looks via the props.

2023-03-08 08:33 UTC, timrombergjakobsson commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +import { formatHtmlPreview } from '../../utils/utils';
There already is a Story for the HTML/CSS. The ```divider.stories.jsx```-file, Or did I misunderstand your suggestion.?

2023-03-08 13:12 UTC, alexandereneroth commented on tegel/src/components/divider/divider-component.scss
> +    box-sizing: border-box;
The mixin also has the benefit of adding border-box to any nested child components i think.
It was something like
`
& * {
  box-sizing: border-box;
}
`
But yea we should probably have it as part of a bigger reset as we've discussed.

2023-03-08 15:13 UTC, alexandereneroth commented on tegel/src/components/divider/divider.tsx
> +        class={`sdds-divider sdds-divider-${this.type} ${this.direction}`}
I think it might be worth cutting the `sdds-` prefix on the class names here, to make it clearer that its not the same as the other classes with the same names in divider.scss

2023-03-08 15:24 UTC, alexandereneroth commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +import { formatHtmlPreview } from '../../utils/utils';
I think what he means is that this file doesn't show the web component. 
You need to put the tag(<sdds-divider>) in the formatHtmlPreview below, and you shouldn't need the styles in here.

2023-03-08 16:07 UTC, alexandereneroth requested changes
Nice work!
I left some comments above/below ☝️ 👇 

Nice to see the test. I think it's good that you use it to make sure that the proper accessibility attributes are there so it works with assistive technologies.

I don't believe we need to test that it has certain classes or children though. 
Although those classes are what makes it work, the presence of those classes/ children don't necessarily prove that it works. It's generally not necessary to test implementation details like that 💡 .

2023-03-10 07:24 UTC, mJarsater commented
Great stuff!🎖️

I would say maybe check with @nathalielindqvist on aligning the stories and their controls to make sure that they are consistent with other stories.

2023-03-10 13:55 UTC, timrombergjakobsson commented
> Great stuff!🎖️
> 
> I would say maybe check with @nathalielindqvist on aligning the stories and their controls to make sure that they are consistent with other stories.

Yes!

2023-03-14 09:37 UTC, alexandereneroth commented
I think there shouldn't be padding on the edges of the line, If you look at the following screenshot, you can see that the line likely reaches the edge of the container:
<img width="399" alt="Screenshot 2023-03-14 at 09 59 44" src="https://user-images.githubusercontent.com/8556022/224958917-a6a43bc6-a2c7-4329-8cc1-4cf80c059281.png">
<img width="471" alt="Screenshot 2023-03-14 at 10 30 28" src="https://user-images.githubusercontent.com/8556022/224958937-1f9b8ed1-f8b4-421f-bbb1-4d1dd1000f6a.png">

2023-03-14 09:44 UTC, alexandereneroth commented on tegel/src/components/divider/divider.tsx
> +  @Prop() type: 'horizontal' | 'vertical' = 'horizontal';
I think it makes more sense to call this prop 'orientation', what do you say?

2023-03-14 09:46 UTC, alexandereneroth commented on tegel/src/components/divider/divider.spec.ts
> +    expect(root.getAttribute('aria-orientation')).toBe('vertical');
Nice!

2023-03-14 10:17 UTC, theJohnnyMe commented
Awesome work! 🚀
I would say after you fix what Alex mentioned in a last comment for prop name, it can get approved ;)

2023-03-14 10:28 UTC, nathalielindqvist commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +      description: 'Choose divider width.',
```suggestion
      description: 'Sets the divider width.',
```

2023-03-14 10:29 UTC, nathalielindqvist commented on tegel/src/components/divider/divider-webcomponent.stories.tsx
> +      description: 'Choose divider height.',
```suggestion
      description: 'Sets the divider height.',
```

2023-03-14 10:34 UTC, nathalielindqvist reviewed
Awesome work! Just added some suggestions on control description updates to align between native and web component, apart from that looking good! 🔥

2023-03-14 10:34 UTC, nathalielindqvist commented on tegel/src/components/divider/divider.tsx
> +  @Prop() type: 'horizontal' | 'vertical' = 'horizontal';
Agreed! I have created a separate ticket for that, so we can align Native and Web Component in the same PR ☺️

2023-03-14 12:34 UTC, theJohnnyMe approved these changes
LGTM! 🤘

2023-03-14 13:53 UTC, merged