fix(banner): correct color in disabled state
scania-digital-design-system/sdds pull request #910
Opened 2023-03-07 08:46 UTC by timrombergjakobsson

**Describe pull-request**  
Now uses the correct color when dropdown is disabled, also moves the inclusion of vars file to global css

**Solving issue**  
Fixes: [DTS-712](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-712)

**How to test**  
Go to storybook link below.
2. Check in Components -> Dropdown, Web Component, toggle disabled state and check that var(--sdds-grey-800) is being used.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Dark/light mode and variants

2023-03-07 09:16 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-vars.scss
> +  --sdds-dropdown-disabled: var(--sdds-grey-800);
From what I can see in Figma this should be grey-400

2023-03-07 09:17 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown.scss
> +      color: var(--sdds-grey-800);
I think these should both use a variable instead.

2023-03-07 09:17 UTC, mJarsater commented on tegel/src/global/global.scss
> +@import 'src/components/dropdown/dropdown-vars';
Nice!

2023-03-07 09:17 UTC, mJarsater requested changes
From what I can see the color was correct. Disabled in figma has color grey-400.

2023-03-07 09:22 UTC, timrombergjakobsson commented on tegel/src/components/dropdown/dropdown-vars.scss
> +  --sdds-dropdown-disabled: var(--sdds-grey-800);
Yes! Your right, it is only dark-mode that should have grey-800.

2023-03-07 09:29 UTC, mJarsater commented on tegel/src/components/dropdown/dropdown-vars.scss
> +  --sdds-dropdown-disabled: var(--sdds-grey-800);
Ah! Great!

2023-03-08 06:39 UTC, nathalielindqvist commented
> From what I can see the color was correct. Disabled in figma has color grey-400.

Yup, light mode has grey-400 for disabled. But the dark mode uses grey-800 :)
![image](https://user-images.githubusercontent.com/48509966/223638001-1fcec853-efa3-425b-a140-320538179ad0.png)

2023-03-08 10:25 UTC, mJarsater approved these changes
LGTM!

2023-03-08 10:34 UTC, merged