feat(tabs): tab item
scania-digital-design-system/sdds pull request #956
Opened 2023-03-20 12:10 UTC by mJarsater

**Describe pull-request**  
This PR introduces 3 new components. folder-, inline- and navigation-tabs-item. These are three generic components that can be used to add a react router Link or NavLink component for the tabs.

**Solving issue**  
Fixes: -

**How to test**  
1. Go to storybook link below.
2. Check in Componets -> Tabs -> Folder/Inline/Navigation tabs
3. Change the "Tab type" to item and try the tabs out.
4. Check that the styling i still correct.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-03-21 07:11 UTC, timrombergjakobsson commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs-item/sdds-navigation-tabs-item.scss
> +    outline: 2px solid var(--sdds-blue-400);
These 2 lines almost feel like they could be a mixin? If we like mixins :). As they are repeated often.

2023-03-21 07:13 UTC, timrombergjakobsson commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs-item/sdds-navigation-tabs-item.scss
> +    outline: 2px solid var(--sdds-blue-400);
```suggestion
    @mixin custom-outline($color, $offset) {
       outline: 2px solid $color;
       outline-offset: $offset;
     }
```

2023-03-21 07:19 UTC, mJarsater commented on tegel/src/components/tabs/navigation-tabs/navigation-tabs-item/sdds-navigation-tabs-item.scss
> +    outline: 2px solid var(--sdds-blue-400);
Yes, already have a mixin for it actuallt @sdds-focus-state. I was playing around with it a bit and that's why it's not using it. Nice catch 🎣

2023-03-21 07:36 UTC, nathalielindqvist commented
This is probably not related directly to this PR, but when going down to mobile size on the Inline Tabs the button to skip-right works well but the button to skip-left only skips in very small increments, so you have to click a lot of times to get back to the start of the tabs. This does not happen with the other tabs versions. Seems like that's not supposed to happen? :)

2023-03-21 08:20 UTC, mJarsater commented
> This is probably not related directly to this PR, but when going down to mobile size on the Inline Tabs the button to skip-right works well but the button to skip-left only skips in very small increments, so you have to click a lot of times to get back to the start of the tabs. This does not happen with the other tabs versions. Seems like that's not supposed to happen? :)

Nice catch, should be fixed now. 🔨

2023-03-21 08:39 UTC, nathalielindqvist approved these changes
Really nice job! I like the more neutral alternative, feels more flexible 🥳 LGTM!

2023-03-22 14:29 UTC, alexandereneroth requested changes
Lets keep this to work more on /test how the tab API could be

2023-03-28 07:56 UTC, alexandereneroth requested changes

2023-03-28 07:56 UTC, alexandereneroth commented on tegel/src/components/tabs/folder-tabs/folder-tabs.tsx
> +          role="list"
I think the role needs to be on the Host element, since the div is inside the shadow dom

2023-04-03 11:18 UTC, merged