fix(side menu): active state background color for header side menu
scania-digital-design-system/sdds pull request #973
Opened 2023-03-22 07:49 UTC by nathalielindqvist

**Describe pull-request**  
Implemented an active state background color for selected menu items in the headers side menu. Previously there was only a hover state background color in mobile view, where the side menu is visible. 

**Solving issue**  
Fixes: [DTS-1393](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1393)

**How to test**  
1. Go to Storybook link below
2. Check in Header -> All Menus
3. Resize the window so the menu items are moved into the side menu
4. Open the side menu and inspect the selected menu item
5. Check in both light and dark mode and compare with Figma

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-03-22 09:52 UTC, EmelieLitwin commented
Collapsed side menu looking a bit wonky, not sure if it should be part of this PR though?
![image](https://user-images.githubusercontent.com/22123579/226866248-ec6cb216-ddfd-4c46-b0b1-c6300d665d0a.png)

2023-03-22 14:26 UTC, alexandereneroth commented on tegel/src/components/header/header.scss
> +
```suggestion
```

Lets remove this

2023-03-22 14:28 UTC, alexandereneroth requested changes
Looks good i think 👍 Just remove the comment and Ill approve :)

2023-03-24 08:14 UTC, alexandereneroth approved these changes
👏

2023-03-24 08:19 UTC, merged