fix(sider-menu): correct color on header in side menu dark mode
scania-digital-design-system/sdds pull request #978
Opened 2023-03-22 15:18 UTC by timrombergjakobsson

**Describe pull-request**  
Correct color for close icons header part. 

**Solving issue**  
Fixes: [#](https://tegel.atlassian.net/browse/DTS-1394)

**How to test**  
1.Go to Storybook link below
2. Check in Header -> Inline Menu, switch to dark mode
Resize the window so the menu items are moved into the side menu
Open the menu and see that the color is the same as Figma.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

**Screenshots** 
Should look like this below.
![Skärmavbild 2023-03-22 kl  16 16 38](https://user-images.githubusercontent.com/201671/226951641-b490e038-435c-4042-b85b-d1eea863c999.png)

2023-03-22 15:37 UTC, timrombergjakobsson commented
> <img alt="Screenshot 2023-03-22 at 16 31 16" width="300" src="https://user-images.githubusercontent.com/8556022/226955719-eeac3371-1c30-486a-bf37-2c73e0d59ae2.png">
> 
> While not technically requested by the JIRA issue, it would be nice if we could fix the borders I hightlighted in red here too ☝️

Sure, I can fix them as well.

2023-03-22 16:14 UTC, alexandereneroth commented on tegel/src/components/header/header-vars.scss
> +  --sdds-nav-item-border-color: var(--sdds-grey-868);
Unfortunately this change changed more than intended:

Before:
<img width="196" alt="Screenshot 2023-03-22 at 17 13 17" src="https://user-images.githubusercontent.com/8556022/226968736-2e98c233-0fc4-4e6c-931d-ea5cdea6fd67.png">

After:
<img width="193" alt="Screenshot 2023-03-22 at 17 13 08" src="https://user-images.githubusercontent.com/8556022/226968775-70ec7d56-6f36-4fb8-bece-1221b1754d5b.png">

2023-03-22 16:14 UTC, alexandereneroth requested changes
see comment

2023-03-23 08:30 UTC, alexandereneroth approved these changes
Nice work!

2023-03-23 09:27 UTC, merged