feat(accordion): cancelable events
scania-digital-design-system/sdds pull request #984
Opened 2023-03-27 11:22 UTC by mJarsater

**Describe pull-request**  
This PR enables for users to cancel the sddsToggle event that is emitted whenever a accordion-item is toggled. It also adds a public method for the users to trigger the event with. Lastly I added a "accordion-item-header" slot that can be used instead of the 'header' prop currently on the component.

**Solving issue**  
Fixes: [DTS-1083](https://tegel.atlassian.net/browse/DTS-1083)

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Accordion
3. Check the readme for the event and the public method.
4. Check out the branch
5. Try preventing an event
6. See it fail to execute

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-03-27 16:37 UTC, alexandereneroth requested changes

2023-03-27 16:37 UTC, alexandereneroth commented on tegel/src/components/accordion/accordion-item/accordion-item.tsx
> +  }
```suggestion
  async toggleAccordionItem() {
  	const toggledExpanded = !this.expanded;
    const event = this.sddsToggle.emit({
      expanded: toggledExpanded,
    });
    if (!event.defaultPrevented) {
      this.expanded = toggledExpanded;
    }
  }
```
This code emits with the expanded state before it is toggled, so it will show the old value, not the new one, which might cause confusion.

In the suggestion i made it so the event emits with the toggled value, but it is not set if default is prevented.

2023-03-27 16:37 UTC, alexandereneroth commented on tegel/src/components/accordion/accordion-item/accordion-item.tsx
> +  /** Method for toggeling the expanded state of the accordion item. */
```suggestion
  /** Method for toggling the expanded state of the accordion item. */
```

2023-03-27 16:44 UTC, mJarsater commented on tegel/src/components/accordion/accordion-item/accordion-item.tsx
> +  }
Yeah I'm not sure how to handle these really. Ideally I would not want to emit a value that's "false".

The code above could just be: 
` async toggleAccordionItem() {
    const event = this.sddsToggle.emit({
      expanded: !this.expanded,
    });
    if (!event.defaultPrevented) {
      this.expanded = !this.expanded;
    }
  }`
  
  We don't really need the temp value. Would should leave a comment explaining it for future reference though

2023-03-28 07:30 UTC, alexandereneroth commented on tegel/src/components/accordion/accordion-item/accordion-item.tsx
> +  }
Yea ChatGPT gave me that as an example to fix it, but then I asked to compare it to the one with the variable it gave me this 🤷 

> Both code snippets achieve the same goal of preventing the expanded state from being toggled if the event default is prevented. The code you provided is a bit more explicit, and it has some advantages:

>1. Readability: By creating a separate variable (nextExpanded) to store the opposite value of the current expanded state, the code becomes more readable and easier to understand.

>2. Maintainability: With a separate variable, it's easier to modify the code in the future if there's any change in the logic of how the next state is calculated.

>3. Debugging: Having a separate variable makes it easier to debug the code if any issues arise since you can directly inspect the nextExpanded value.

But don't think it really matters which way TBH

2023-03-28 07:32 UTC, alexandereneroth approved these changes
👍

2023-03-28 13:51 UTC, merged