fix(table): inline json dummy data
scania-digital-design-system/sdds pull request #991
Opened 2023-03-29 10:46 UTC by timrombergjakobsson

**Describe pull-request**  
A bug report in the support channel revealed that when using the @scania/tegel package in a stencil.js project threw an error that was traced back to the external dummy-json file being used in the table-body.tsx-file. Proposal is to inline it instead. This has been tried and verified in a local stencil.js project. 

**Solving issue**  
_In case of GitHub issue add # plus the number of the issue (for example #123) OR if it is Azure then AB# and number of ticket_
Fixes: [DTS-1459](https://tegel.atlassian.net/jira/software/projects/DTS/boards/1?selectedIssue=DTS-1459)

**How to test**  
_Add description how to test if possible_
1. Go to Storybook
2. Check in Components -> Table components, and see that the data is displayed.

**Suggested test steps**
- [ ] Browser testing (Chrome, Safari, Firefox) 
- [ ] Keyboard operability
- [ ] Interactive elements have labels.
- [ ] Storybook controls
- [ ] Design/controls/props is aligned with other components 
- [ ] Dark/light mode and variants 
- [ ] Input fields – values should be displayed properly 
- [ ] Events

2023-03-29 10:48 UTC, timrombergjakobsson commented on tegel/src/components/modal/modal.tsx
> -        event.stopPropagation();
Note this one should not be here. It is opened in this PR: https://github.com/scania-digital-design-system/sdds/pull/987

2023-03-29 13:56 UTC, nathalielindqvist approved these changes
LGTM! 👌

2023-04-03 07:35 UTC, mJarsater requested changes

2023-04-03 07:35 UTC, mJarsater commented on tegel/src/components/data-table/table-body/table-body.tsx
> +  @Prop() enableJsonData: boolean = false;
Maybe we shouldn't rename this? DummyData highlights that this is something that should not be used by a user, and that it's more for testing. I would recommend that we keep it as enableDummyData and then create a ticket in the backlog to remove it before 1.0.

2023-04-03 07:40 UTC, timrombergjakobsson commented on tegel/src/components/data-table/table-body/table-body.tsx
> +  @Prop() enableJsonData: boolean = false;
@mJarsater I agree, Ill revert!

2023-04-03 11:19 UTC, mJarsater approved these changes
🦄

2023-04-03 11:48 UTC, merged