fix(global): bg and color
scania-digital-design-system/sdds pull request #998
Opened 2023-04-03 11:05 UTC by mJarsater

**Describe pull-request**  
The global.scss for background and color was "too weak", it was getting picked up by the table because it was not specific enough. This PR strengthens those rules. 

If the user want dark mode with secondary variant globally now they would have to do is like this:

<div class="App root sdds-mode-dark sdds-mode-variant-secondary"></div>

They have to be specified on the same element.

**Solving issue**  
Fixes: https://tegel.atlassian.net/browse/DTS-1477

**How to test**  
1. Go to storybook link below.
2. Check in Components -> Data-table -> WC
3. Check that primary vs secondary is correct.
4. Check the "root" of the HTML.
5. See that it has the correct bg and color based on theme.

2023-04-03 12:49 UTC, nathalielindqvist approved these changes
LGTM :)

2023-04-03 15:06 UTC, EmelieLitwin commented
Not really part of the PR but in most components primary/secondary mode variant variables have been handled like this:
![image](https://user-images.githubusercontent.com/22123579/229550129-937869c2-7b21-4d7d-ba05-2c8ab590c976.png)

E.i. all the background colors etc have been declared at the same place above. Should we do it like that in the data table as well?

2023-04-03 15:18 UTC, mJarsater commented
> Not really part of the PR but in most components primary/secondary mode variant variables have been handled like this: ![image](https://user-images.githubusercontent.com/22123579/229550129-937869c2-7b21-4d7d-ba05-2c8ab590c976.png)
> 
> E.i. all the background colors etc have been declared at the same place above. Should we do it like that in the data table as well?

Yes, I think that would be a good approach 👍

2023-04-04 09:24 UTC, alexandereneroth commented on tegel/src/global/global.scss
>  .sdds-mode-light {
```suggestion
:root,
.sdds-mode-light {
```

2023-04-04 09:58 UTC, alexandereneroth requested changes
I think the issue is rather that the background style is set on the :host of the webcomponent (&lt;sdds-table-body-row>), I think we should not style :host as styles put on :host are outside the shadow dom and are not protected (as this issue demonstrates).
It would be better if we put the background on an inner element inside :host instead.

2023-04-11 12:40 UTC, merged